# Generated by Django 4.2.7 on 2025-07-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("legal", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldispute",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="amendments",
                to="legal.contract",
            ),
        ),
        migrations.AddField(
            model_name="contractamendment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="party_a_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="party_a_contracts",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="party_b_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="party_b_contracts",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="creditor_content_type",
            field=models.ForeignKey(
                help_text="The type of entity that is the creditor.",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims_as_creditor",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="currency",
            field=models.ForeignKey(
                help_text="The currency of the claim amount.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="debtor_content_type",
            field=models.ForeignKey(
                help_text="The type of entity that is the debtor.",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims_as_debtor",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activecredit",
            name="cr_content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_entries",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="activecredit",
            name="dr_content_type",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debit_entries",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="activecredit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
