# Generated by Django 4.2.7 on 2025-08-18 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activecredit",
            name="user",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="user",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="user",
        ),
        migrations.RemoveField(
            model_name="contractamendment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="legaldispute",
            name="user",
        ),
    ]
