# Generated by Django 4.2.7 on 2025-09-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_initial"),
        ("legal", "0003_remove_activecredit_user_remove_claim_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claim",
            name="creditor_content_type",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="creditor_object_id",
        ),
        migrations.AddField(
            model_name="claim",
            name="client",
            field=models.ForeignKey(
                default=1,
                help_text="The client associated with the claim.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="claims",
                to="clients.client",
            ),
            preserve_default=False,
        ),
    ]
