# Generated by Django 4.2.7 on 2025-09-25 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("clients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("legal", "0004_remove_claim_creditor_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="closed_date",
            field=models.DateField(blank=True, null=True, verbose_name="Closed Date"),
        ),
        migrations.AddField(
            model_name="claim",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the claim is closed.",
                verbose_name="Is Closed",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the claim has been verified.",
                verbose_name="Is Verified",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="verified_date",
            field=models.DateField(blank=True, null=True, verbose_name="Verified Date"),
        ),
        migrations.AlterUniqueTogether(
            name="claim",
            unique_together={
                (
                    "client",
                    "debtor_content_type",
                    "debtor_object_id",
                    "account_number",
                    "amount",
                    "claim_date",
                )
            },
        ),
    ]
