# Generated by Django 4.2.7 on 2025-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "enquired_entity_object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the entity (Individual or Company) that was enquired about."
                    ),
                ),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
                "db_table": "enquiries",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("parameters", models.JSONField()),
                ("generated_file", models.FileField(upload_to="generated_reports/")),
            ],
            options={
                "verbose_name": "generated report",
                "verbose_name_plural": "generated reports",
                "db_table": "generated_reports",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("lease", "Lease Report"),
                            ("financial", "Financial Report"),
                            ("property", "Property Report"),
                            ("tenant", "Tenant Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("template_file", models.FileField(upload_to="report_templates/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "report template",
                "verbose_name_plural": "report templates",
                "db_table": "report_templates",
            },
        ),
    ]
