# Generated by Django 4.2.7 on 2025-11-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("lease", "Lease Report"),
                            ("financial", "Financial Report"),
                            ("property", "Property Report"),
                            ("tenant", "Tenant Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("template_file", models.FileField(upload_to="report_templates/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "report template",
                "verbose_name_plural": "report templates",
                "db_table": "report_templates",
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("parameters", models.JSONField()),
                ("generated_file", models.FileField(upload_to="generated_reports/")),
                (
                    "report_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.reporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "generated report",
                "verbose_name_plural": "generated reports",
                "db_table": "generated_reports",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "enquired_entity_object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the entity (Individual or Company) that was enquired about."
                    ),
                ),
                (
                    "enquired_entity_content_type",
                    models.ForeignKey(
                        help_text="The type of entity that was enquired about.",
                        limit_choices_to=models.Q(
                            models.Q(
                                ("app_label", "individuals"), ("model", "individual")
                            ),
                            models.Q(
                                ("app_label", "companies"), ("model", "companybranch")
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enquiries_for_entity_type",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enquiry",
                "verbose_name_plural": "Enquiries",
                "db_table": "enquiries",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
    ]
