# Generated by Django 4.2.7 on 2025-07-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("reporting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="report_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.reporttemplate",
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="enquired_entity_content_type",
            field=models.ForeignKey(
                help_text="The type of entity that was enquired about.",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enquiries_for_entity_type",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
