# Generated by Django 4.2.7 on 2025-07-09 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="enquiry",
            table="enquiries",
        ),
        migrations.AlterModelTable(
            name="generatedreport",
            table="generated_reports",
        ),
        migrations.AlterModelTable(
            name="reporttemplate",
            table="report_templates",
        ),
    ]
