# Generated by Django 4.2.7 on 2025-08-18 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="user",
        ),
        migrations.RemoveField(
            model_name="generatedreport",
            name="user",
        ),
        migrations.RemoveField(
            model_name="reporttemplate",
            name="user",
        ),
    ]
