# Generated by Django 4.2.7 on 2025-07-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Unique registration number of the company.",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "registration_name",
                    models.CharField(
                        help_text="The official registered name of the company.",
                        max_length=255,
                    ),
                ),
                (
                    "trading_name",
                    models.CharField(
                        blank=True,
                        help_text="The name the company trades under, if different from registration name.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "legal_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("private", "Private Limited"),
                            ("public", "Public Limited"),
                            ("government", "Government"),
                            ("ngo", "NGO"),
                            ("other", "Other"),
                        ],
                        default="private",
                        help_text="The legal status or type of the company.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "date_of_incorporation",
                    models.DateField(
                        blank=True,
                        help_text="The date the company was officially incorporated.",
                        null=True,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        help_text="The industry sector the company operates in.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the company's details have been verified.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "db_table": "company",
                "ordering": ["registration_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "branch_name",
                    models.CharField(
                        help_text="The name of the branch.", max_length=255
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Indicates if the branch is deleted."
                    ),
                ),
                (
                    "is_headquarters",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this branch is the headquarters.",
                    ),
                ),
            ],
            options={
                "verbose_name": "company branch",
                "verbose_name_plural": "company branches",
                "db_table": "company_branch",
                "ordering": ["company__registration_name", "branch_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "company",
                    models.OneToOneField(
                        help_text="The company this profile belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to="companies.company",
                    ),
                ),
                (
                    "trading_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("LIQUIDATION", "In Liquidation"),
                            ("BUSINESS_RESCUE", "Business Rescue"),
                            ("DEREGISTERED", "Deregistered"),
                            ("PENDING_REGISTRATION", "Pending Registration"),
                        ],
                        help_text="Current trading status of the company.",
                        max_length=50,
                        null=True,
                        verbose_name="Trading Status",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True,
                        help_text="General mobile phone number for the company.",
                        max_length=20,
                        null=True,
                        verbose_name="Mobile Phone",
                    ),
                ),
                (
                    "landline_phone",
                    models.CharField(
                        blank=True,
                        help_text="General landline phone number for the company.",
                        max_length=20,
                        null=True,
                        verbose_name="Landline Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="General email address for the company.",
                        max_length=255,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo image file.",
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="Company Logo",
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        blank=True,
                        help_text="The official registration date of the company profile.",
                        null=True,
                        verbose_name="Registration Date",
                    ),
                ),
                (
                    "tin_number",
                    models.CharField(
                        blank=True,
                        help_text="Business Partner Number.",
                        max_length=255,
                        null=True,
                        verbose_name="BP Number",
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True,
                        help_text="Value Added Tax (VAT) registration number.",
                        max_length=255,
                        null=True,
                        verbose_name="VAT Number",
                    ),
                ),
                (
                    "number_of_employees",
                    models.IntegerField(
                        blank=True,
                        help_text="Approximate number of employees.",
                        null=True,
                        verbose_name="Number of Employees",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Official website URL of the company.",
                        max_length=255,
                        null=True,
                        verbose_name="Website",
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GROWING", "Growing"),
                            ("STABLE", "Stable"),
                            ("DECLINING", "Declining"),
                            ("NEW", "New"),
                        ],
                        help_text="Current growth trend of the company.",
                        max_length=50,
                        null=True,
                        verbose_name="Company Trend",
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Twitter URL",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Facebook URL",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Instagram URL",
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="LinkedIn URL",
                    ),
                ),
                (
                    "operations",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of company operations.",
                        null=True,
                        verbose_name="Operations Details",
                    ),
                ),
                (
                    "risk_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("VERY_HIGH", "Very High Risk"),
                        ],
                        default="LOW",
                        help_text="Assessed risk classification of the company.",
                        max_length=20,
                        null=True,
                        verbose_name="Risk Class",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Main bank account number for the company.",
                        max_length=255,
                        null=True,
                        verbose_name="Account Number",
                    ),
                ),
                (
                    "is_under_judicial",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_INFO", "No Information"),
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("PENDING", "Pending Assessment"),
                        ],
                        default="NO_INFO",
                        help_text="Indicates if the company is currently under judicial management or liquidation.",
                        max_length=20,
                        null=True,
                        verbose_name="Is Under Judicial Process",
                    ),
                ),
                (
                    "is_suspended",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the company's services are currently suspended.",
                        verbose_name="Is Suspended",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
                "db_table": "company_profile",
            },
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "contact_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary", "Primary Contact"),
                            ("finance", "Finance Contact"),
                            ("technical", "Technical Contact"),
                            ("other", "Other"),
                        ],
                        help_text="The type of contact this person represents (e.g., primary, finance).",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the primary contact for its context.",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="The position or role of the contact person.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="The company branch this contact person is associated with.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="companies.companybranch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Person",
                "verbose_name_plural": "Contact Persons",
                "db_table": "contact_person",
                "ordering": ["-date_created"],
            },
        ),
    ]
