# Generated by Django 4.2.7 on 2025-07-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("individuals", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="individual",
            field=models.ForeignKey(
                blank=True,
                help_text="The individual record if this contact person is also an Individual.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_as_person",
                to="individuals.individual",
            ),
        ),
    ]
