# Generated by Django 4.2.7 on 2025-07-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="company",
            field=models.ForeignKey(
                help_text="The company this branch belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="contactperson",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contact_type", "primary")),
                fields=("branch", "contact_type"),
                name="unique_primary_branch_contact",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="contact_person",
            field=models.ForeignKey(
                blank=True,
                help_text="The primary contact person for this company profile.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies_as_primary_contact",
                to="companies.contactperson",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="companybranch",
            constraint=models.UniqueConstraint(
                fields=("company", "branch_name"), name="unique_branch_name_per_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(("registration_name__isnull", True), _negated=True),
                fields=("registration_name",),
                name="unique_registration_name_company",
            ),
        ),
    ]
