# Generated by Django 4.2.7 on 2025-08-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
        migrations.RemoveField(
            model_name="companybranch",
            name="user",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="contactperson",
            name="user",
        ),
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="tin_number",
            field=models.CharField(
                blank=True,
                help_text="Tax Identification Number.",
                max_length=255,
                null=True,
                verbose_name="Tin Number",
            ),
        ),
    ]
