# Generated by Django 4.2.7 on 2025-11-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Unique registration number of the company.",
                max_length=50,
                null=True,
            ),
        ),
    ]
