# Generated by Django 4.2.7 on 2025-07-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="subscription_category",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="subscription_contract",
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="is_under_judicial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_INFO", "No Information"),
                    ("YES", "Yes"),
                    ("NO", "No"),
                    ("PENDING", "Pending Assessment"),
                ],
                default="NO_INFO",
                help_text="Indicates if the company is currently under judicial management or liquidation.",
                max_length=20,
                null=True,
                verbose_name="Is Under Judicial Process",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="risk_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOW", "Low Risk"),
                    ("MEDIUM", "Medium Risk"),
                    ("HIGH", "High Risk"),
                    ("VERY_HIGH", "Very High Risk"),
                ],
                default="LOW",
                help_text="Assessed risk classification of the company.",
                max_length=20,
                null=True,
                verbose_name="Risk Class",
            ),
        ),
    ]
