# Generated by Django 4.2.7 on 2025-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_remove_company_user_remove_companybranch_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybranch",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="General email address for the branch.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="General phone number for the branch.",
                max_length=20,
                null=True,
            ),
        ),
    ]
