# Generated by Django 4.2.7 on 2025-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_remove_companyprofile_subscription_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companybranch",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Indicates if the branch is deleted."
            ),
        ),
        migrations.AddField(
            model_name="companybranch",
            name="is_headquarters",
            field=models.BooleanField(
                default=False, help_text="Indicates if this branch is the headquarters."
            ),
        ),
    ]
