# Generated by Django 4.2.7 on 2025-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_companybranch_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="legal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("private", "Private Limited"),
                    ("public", "Public Limited"),
                    ("government", "Government"),
                    ("ngo", "NGO"),
                    ("other", "Other"),
                ],
                default="private",
                help_text="The legal status or type of the company.",
                max_length=20,
                null=True,
            ),
        ),
    ]
