# Generated by Django 4.2.7 on 2025-10-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_companybranch_email_companybranch_phone"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="companyprofile",
        #     name="account_number",
        #     field=models.CharField(
        #         blank=True,
        #         help_text="Unique customer account number for the company.",
        #         max_length=255,
        #         null=True,
        #         unique=True,
        #         verbose_name="Account Number",
        #     ),
        # ),
    ]
