# Generated by Django 4.2.7 on 2025-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_companyprofile_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="Unique customer account number for the company.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Account Number",
            ),
        ),
    ]
