# Generated by Django 4.2.7 on 2025-07-18 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_company_legal_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companyprofile",
            old_name="bp_number",
            new_name="tin_number",
        ),
    ]
