# Generated by Django 4.2.7 on 2025-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Under Maintenance"),
                            ("sold", "Sold"),
                            ("partially_occupied", "Partially Occupied"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="In square meters",
                        max_digits=10,
                    ),
                ),
                ("is_furnished", models.BooleanField(default=False)),
                (
                    "total_number_of_units",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of units in the property"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        help_text="Additional features of the property",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "property type",
                "verbose_name_plural": "property types",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("unit_number", models.CharField(default=0, max_length=50)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("office", "Office"),
                            ("retail", "Retail Space"),
                            ("warehouse", "Warehouse"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                (
                    "number_of_rooms",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of rooms in the unit"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        help_text="Additional features of the unit",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "unit",
                "verbose_name_plural": "units",
            },
        ),
    ]
