# Generated by Django 4.2.7 on 2025-07-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                            ("sold", "Sold"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("year_built", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2, help_text="In square meters", max_digits=10
                    ),
                ),
                ("is_furnished", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "property",
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "property type",
                "verbose_name_plural": "property types",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("unit_number", models.CharField(default=0, max_length=50)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment"),
                            ("HOUSE", "House"),
                            ("OFFICE", "Office"),
                            ("RETAIL", "Retail Space"),
                            ("WAREHOUSE", "Warehouse"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
                (
                    "floor_number",
                    models.PositiveIntegerField(
                        default=0, help_text="Floor number where the unit is located"
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of bedrooms in the unit"
                    ),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of bathrooms in the unit"
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In square meters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vacant", "Vacant"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="vacant",
                        max_length=20,
                    ),
                ),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("features", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "unit",
                "verbose_name_plural": "units",
            },
        ),
    ]
