# Generated by Django 4.2.7 on 2025-07-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="area",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="bathrooms",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="bedrooms",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="deposit_amount",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="floor_number",
        ),
        migrations.AddField(
            model_name="property",
            name="features",
            field=models.JSONField(
                blank=True, help_text="Additional features of the property", null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="total_number_of_units",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of units in the property"
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="number_of_rooms",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of rooms in the unit"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="features",
            field=models.JSONField(
                blank=True, help_text="Additional features of the unit", null=True
            ),
        ),
    ]
