# Generated by Django 4.2.7 on 2025-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_remove_property_user_remove_propertytype_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="monthly_rent",
        ),
    ]
