# Generated by Django 4.2.7 on 2025-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_remove_unit_monthly_rent"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
