# Generated by Django 4.2.7 on 2025-08-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0006_property_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("office", "Office"),
                    ("retail", "Retail Space"),
                    ("warehouse", "Warehouse"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
    ]
