# Generated by Django 4.2.7 on 2025-09-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0007_alter_unit_unit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="total_area",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="In square meters", max_digits=10
            ),
        ),
    ]
