# Generated by Django 4.2.7 on 2025-09-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0008_alter_property_total_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
