# Generated by Django 4.2.7 on 2025-09-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_initial"),
        ("properties", "0009_alter_property_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="managing_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="clients.client",
            ),
        ),
    ]
