# Generated by Django 4.2.7 on 2025-10-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0010_property_managing_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("vacant", "Vacant"),
                    ("occupied", "Occupied"),
                    ("maintenance", "Under Maintenance"),
                    ("sold", "Sold"),
                    ("partially_occupied", "Partially Occupied"),
                ],
                default="vacant",
                max_length=20,
            ),
        ),
    ]
