# Generated by Django 4.2.7 on 2025-07-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leases", "0001_initial"),
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="requested_entity_content_type",
            field=models.ForeignKey(
                help_text="The type of entity for whom the OTP is requested.",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps_for_entity_type",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="debtorintelligencenote",
            name="client_content_type",
            field=models.ForeignKey(
                help_text="The type of entity this note is about (debtor).",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debtor_intelligence_notes_as_client",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="debtorintelligencenote",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communicationhistoryreminder",
            name="client_content_type",
            field=models.ForeignKey(
                help_text="The type of entity this reminder is about.",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders_as_client",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="communicationhistoryreminder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communicationattachment",
            name="communication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="communications.communication",
            ),
        ),
        migrations.AddField(
            model_name="communicationattachment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="related_lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="sent_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_communications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commshistmessage",
            name="client_content_type",
            field=models.ForeignKey(
                help_text="The type of entity this message is to/from.",
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_as_client",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="commshistmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
