# Generated by Django 4.2.7 on 2025-08-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0006_alter_leasecharge_charge_type"),
        (
            "accounting",
            "0003_alter_cashbook_options_alter_cashbookentry_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="leases.lease",
            ),
        ),
    ]
