# Generated by Django 4.2.7 on 2025-11-21 08:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_alter_vatsetting_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashsale",
            name="company",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="is_individual",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="total_excluding_vat",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="vat_total",
        ),
        migrations.AddField(
            model_name="cashsale",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.customer",
            ),
        ),
        migrations.AlterField(
            model_name="cashsale",
            name="sale_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
