# Generated by Django 4.2.7 on 2025-11-27 09:46

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0004_alter_company_registration_number"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounting", "0003_alter_vatsetting_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "period_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_open", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Accounting Period",
                "verbose_name_plural": "Accounting Periods",
                "ordering": ["financial_year", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="AccountSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code_prefix", models.CharField(max_length=3)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Account Subtype",
                "verbose_name_plural": "Account Subtypes",
                "ordering": ["account_type", "code_prefix"],
            },
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                            ("contra_asset", "Contra Asset"),
                            ("contra_liability", "Contra Liability"),
                            ("contra_equity", "Contra Equity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Account Type",
                "verbose_name_plural": "Account Types",
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="BalanceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("as_of_date", models.DateField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Balance Sheet",
                "verbose_name_plural": "Balance Sheets",
                "ordering": ["-as_of_date"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("account_number", models.CharField(max_length=50, unique=True)),
                ("account_name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "opening_balance_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
                "ordering": ["bank_name", "account_number"],
            },
        ),
        migrations.CreateModel(
            name="CashReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "receipt_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("receipt_date", models.DateField(default=django.utils.timezone.now)),
                ("received_from", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Cash Receipt",
                "verbose_name_plural": "Cash Receipts",
                "ordering": ["-receipt_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cost Center",
                "verbose_name_plural": "Cost Centers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-effective_date", "base_currency", "target_currency"],
            },
        ),
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="IncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Income Statement",
                "verbose_name_plural": "Income Statements",
                "ordering": ["-period__end_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TaxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tax Type",
                "verbose_name_plural": "Tax Types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TrialBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trial Balance",
                "verbose_name_plural": "Trial Balances",
                "ordering": ["-period__end_date", "-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="TrialBalanceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "debit_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "credit_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
            ],
            options={
                "verbose_name": "Trial Balance Item",
                "verbose_name_plural": "Trial Balance Items",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("vendor_code", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "payment_terms",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days for payment"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("on_hold", models.BooleanField(default=False)),
                ("hold_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["vendor_code"],
            },
        ),
        migrations.RemoveField(
            model_name="cashbook",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="cashbook",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="cashbook",
            name="general_ledger_account",
        ),
        migrations.RemoveField(
            model_name="cashbook",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="cashbookentry",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="cashbookentry",
            name="transaction_type",
        ),
        migrations.RemoveField(
            model_name="cashbookentry",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="cashbook",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="company",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="payment_type",
        ),
        migrations.RemoveField(
            model_name="cashsale",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="currencyrate",
            name="base_currency",
        ),
        migrations.RemoveField(
            model_name="currencyrate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="currencyrate",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="currencyrate",
            name="updated_by",
        ),
        migrations.AlterUniqueTogether(
            name="transactionlineitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="transactionlineitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="transactionlineitem",
            name="sales_item",
        ),
        migrations.RemoveField(
            model_name="vatsetting",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="vatsetting",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={
                "ordering": ["currency_code"],
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["customer_code"],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="generalledgeraccount",
            options={
                "ordering": ["account_number"],
                "verbose_name": "General Ledger Account",
                "verbose_name_plural": "General Ledger Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-invoice_date", "-invoice_number"],
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-entry_date", "-id"],
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="ledgertransaction",
            options={
                "ordering": ["journal_entry__entry_date", "id"],
                "verbose_name": "Ledger Transaction",
                "verbose_name_plural": "Ledger Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payment_date", "-id"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "ordering": ["name"],
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="salescategory",
            options={
                "ordering": ["code"],
                "verbose_name": "Sales Category",
                "verbose_name_plural": "Sales Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="salesitem",
            options={
                "ordering": ["item_code"],
                "verbose_name": "Sales Item",
                "verbose_name_plural": "Sales Items",
            },
        ),
        migrations.RenameField(
            model_name="generalledgeraccount",
            old_name="is_secondary_currency",
            new_name="is_contra_account",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="total_inclusive",
            new_name="discount_amount",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="description",
            new_name="notes",
        ),
        migrations.RemoveField(
            model_name="generalledgeraccount",
            name="account_sector",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="document_number",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="is_invoiced",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="is_recurring",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="lease",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="next_invoice_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="original_invoice",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="sale_date",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="date",
        ),
        migrations.RemoveField(
            model_name="ledgertransaction",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="ledgertransaction",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="ledgertransaction",
            name="debit",
        ),
        migrations.RemoveField(
            model_name="ledgertransaction",
            name="entry",
        ),
        migrations.RemoveField(
            model_name="ledgertransaction",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="cashbook",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="payment_method_name",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="item_id",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="sales_account",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="tax_configuration",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="unit_name",
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="unit_price_currency",
        ),
        migrations.AddField(
            model_name="currency",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_base_currency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="accounts_receivable_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "account_number__startswith": "11",
                    "account_type__account_type": "asset",
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_accounts",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="hold_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="on_hold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms",
            field=models.PositiveIntegerField(
                default=30, help_text="Number of days for payment"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="account_class",
            field=models.CharField(
                choices=[
                    ("balance_sheet", "Balance Sheet"),
                    ("income_statement", "Income Statement"),
                ],
                default="balance_sheet",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="balance_last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="is_system_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="opening_balance_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_accounts",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="requires_cost_center",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="requires_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="balance_due",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("1.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="posted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="terms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("general", "General Journal"),
                    ("sales", "Sales Journal"),
                    ("purchase", "Purchase Journal"),
                    ("cash_receipts", "Cash Receipts Journal"),
                    ("cash_disbursements", "Cash Disbursements Journal"),
                    ("adjusting", "Adjusting Entry"),
                    ("closing", "Closing Entry"),
                    ("reversing", "Reversing Entry"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_posted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_reversed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reversal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_entries",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reviewed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="source_document",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="total_credit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="total_debit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="credit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="debit_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="cash_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "account_number__startswith": "10",
                    "account_type__account_type": "asset",
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_received",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_number",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="salescategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salescategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salescategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="accounting.salescategory",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="cost_of_sales_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"account_type__account_type": "expense"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_sales_items",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="income_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"account_type__account_type": "revenue"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_items",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"account_type__account_type": "asset"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_items",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="item_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="minimum_stock",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="track_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="generalledgeraccount",
            name="account_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="generalledgeraccount",
            name="account_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="accounting.customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("fiscal", "Fiscal Invoice"),
                    ("proforma", "Proforma Invoice"),
                    ("recurring", "Recurring Invoice"),
                ],
                default="fiscal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("partially_paid", "Partially Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled"),
                    ("written_off", "Written Off"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ledgertransaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="accounting.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="salescategory",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="accounting.salescategory",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_code"], name="accounting__custome_afdc48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["is_active"], name="accounting__is_acti_2771c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generalledgeraccount",
            index=models.Index(
                fields=["account_number"], name="accounting__account_d29f98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generalledgeraccount",
            index=models.Index(
                fields=["is_active"], name="accounting__is_acti_e20af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="accounting__invoice_f5b9b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["customer", "invoice_date"],
                name="accounting__custome_5ba5c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="accounting__status_3055e0_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_date"], name="accounting__entry_d_79c286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_type"], name="accounting__entry_t_5e6cde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["is_posted"], name="accounting__is_post_95b69a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["account", "journal_entry"],
                name="accounting__account_356654_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="accounting__content_e6ee95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["item_code"], name="accounting__item_co_f2007f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["category"], name="accounting__categor_23b8b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesitem",
            index=models.Index(
                fields=["is_active"], name="accounting__is_acti_e4d9c7_idx"
            ),
        ),
        migrations.DeleteModel(
            name="AccountSector",
        ),
        migrations.DeleteModel(
            name="CashBook",
        ),
        migrations.DeleteModel(
            name="CashbookEntry",
        ),
        migrations.DeleteModel(
            name="CashSale",
        ),
        migrations.DeleteModel(
            name="CreditNote",
        ),
        migrations.DeleteModel(
            name="CurrencyRate",
        ),
        migrations.DeleteModel(
            name="TransactionLineItem",
        ),
        migrations.DeleteModel(
            name="TransactionType",
        ),
        migrations.DeleteModel(
            name="VATSetting",
        ),
        migrations.AddField(
            model_name="vendor",
            name="accounts_payable_account",
            field=models.ForeignKey(
                limit_choices_to={
                    "account_number__startswith": "21",
                    "account_type__account_type": "liability",
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_accounts",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.companybranch",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trialbalanceitem",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="trialbalanceitem",
            name="trial_balance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="accounting.trialbalance",
            ),
        ),
        migrations.AddField(
            model_name="trialbalance",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trialbalance",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trial_balances",
                to="accounting.accountingperiod",
            ),
        ),
        migrations.AddField(
            model_name="taxtype",
            name="payable_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"account_type__account_type": "liability"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tax_payable_types",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="taxtype",
            name="receivable_account",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"account_type__account_type": "asset"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tax_receivable_types",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="sales_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.salesitem"
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="incomestatement",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="income_statements",
                to="accounting.accountingperiod",
            ),
        ),
        migrations.AddField(
            model_name="financialyear",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_financial_years",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="base_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_rates",
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="target_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_rates",
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_cost_centers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="parent_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_centers",
                to="accounting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="cashreceipt",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="cashreceipt",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashreceipt",
            name="income_account",
            field=models.ForeignKey(
                limit_choices_to={"account_type__account_type": "revenue"},
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="cashreceipt",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_receipt",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="cashreceipt",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.currency"
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="gl_account",
            field=models.OneToOneField(
                limit_choices_to={
                    "account_number__startswith": "10",
                    "account_type__account_type": "asset",
                },
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="balancesheet",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_sheets",
                to="accounting.accountingperiod",
            ),
        ),
        migrations.AddField(
            model_name="accountsubtype",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtypes",
                to="accounting.accounttype",
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountingperiod",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="accounting.financialyear",
            ),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="account_subtype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="accounting.accountsubtype",
            ),
        ),
        migrations.AddField(
            model_name="generalledgeraccount",
            name="account_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gl_accounts",
                to="accounting.accounttype",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="accounting_period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_entries",
                to="accounting.accountingperiod",
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="accounting.costcenter",
            ),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="tax_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.taxtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trialbalanceitem",
            unique_together={("trial_balance", "account")},
        ),
        migrations.AddConstraint(
            model_name="financialyear",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("base_currency", "target_currency", "effective_date")},
        ),
        migrations.AddConstraint(
            model_name="accountingperiod",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="period_end_date_after_start_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountingperiod",
            unique_together={("financial_year", "period_number")},
        ),
    ]
