# Generated by Django 4.2.7 on 2025-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0004_alter_invoice_lease"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
