# Generated by Django 4.2.7 on 2025-11-28 07:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0004_accountingperiod_accountsubtype_accounttype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "receipt_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("sale_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("customer_display_name", models.CharField(max_length=255)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("check", "Check"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "amount_tendered",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "change_given",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cash_account",
                    models.ForeignKey(
                        limit_choices_to={
                            "account_number__startswith": "10",
                            "account_type__account_type": "asset",
                        },
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sales",
                        to="accounting.generalledgeraccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_sales",
                        to="accounting.customer",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_sale",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "sales_account",
                    models.ForeignKey(
                        limit_choices_to={"account_type__account_type": "revenue"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sales_revenue",
                        to="accounting.generalledgeraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Sale",
                "verbose_name_plural": "Cash Sales",
                "ordering": ["-sale_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CashSaleLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cash_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="accounting.cashsale",
                    ),
                ),
                (
                    "sales_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sale_line_items",
                        to="accounting.salesitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash Sale Line Item",
                "verbose_name_plural": "Cash Sale Line Items",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="cashsale",
            index=models.Index(
                fields=["receipt_number"], name="accounting__receipt_34bdf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashsale",
            index=models.Index(
                fields=["sale_date"], name="accounting__sale_da_c8d1a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cashsale",
            index=models.Index(
                fields=["customer"], name="accounting__custome_e84952_idx"
            ),
        ),
    ]
