# Generated by Django 4.2.7 on 2025-08-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0011_remove_lease_deposit_amount_and_more"),
        ("accounting", "0005_invoice_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="company",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="is_individual",
        ),
        migrations.AddField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="leases.leasetenant",
            ),
        ),
    ]
