# Generated by Django 4.2.7 on 2025-11-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0005_cashsale_cashsalelineitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttype",
            name="code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("asset", "Asset"),
                    ("liability", "Liability"),
                    ("equity", "Equity"),
                    ("revenue", "Revenue"),
                    ("expense", "Expense"),
                    ("contra_asset", "Contra Asset"),
                    ("contra_liability", "Contra Liability"),
                    ("contra_equity", "Contra Equity"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="normal_balance",
            field=models.CharField(
                blank=True,
                choices=[("debit", "Debit"), ("credit", "Credit")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generalledgeraccount",
            name="account_number",
            field=models.CharField(max_length=10),
        ),
    ]
