# Generated by Django 4.2.7 on 2025-08-29 13:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounting",
            "0006_remove_invoice_company_remove_invoice_individual_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("partially_paid", "Partially Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
