# Generated by Django 4.2.7 on 2025-12-04 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0008_taxtype_created_by_taxtype_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="source",
            field=models.CharField(default="Currency Settings", max_length=255),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="effective_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
