# Generated by Django 4.2.7 on 2025-09-05 13:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_remove_subscription_used_slots_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0002_initial"),
        ("accounting", "0009_disbursement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
        migrations.CreateModel(
            name="ServiceStandardPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "individual_charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Individual Charge",
                    ),
                ),
                (
                    "company_charge",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Company Charge"
                    ),
                ),
                (
                    "current_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="The current conversion rate if this pricing involves currency conversion.",
                        max_digits=12,
                        verbose_name="Current Rate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="The currency of the standard charges.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standard_pricing",
                        to="accounting.currency",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The service this standard pricing applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_pricing_options",
                        to="subscriptions.services",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Standard Pricing",
                "verbose_name_plural": "Standard Pricing",
                "ordering": ["-date_created"],
                "abstract": False,
                "unique_together": {("service", "currency")},
            },
        ),
        migrations.CreateModel(
            name="ServiceSpecialPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "individual_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Special charge amount for individuals.",
                        max_digits=12,
                        verbose_name="Individual Charge",
                    ),
                ),
                (
                    "company_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Special charge amount for companies.",
                        max_digits=12,
                        verbose_name="Company Charge",
                    ),
                ),
                (
                    "client_customer",
                    models.OneToOneField(
                        help_text="The specific client this special pricing is for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_pricing",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="The currency of the special charges.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="special_pricing",
                        to="accounting.currency",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The service this special pricing applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_pricing_options",
                        to="subscriptions.services",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Pricing",
                "verbose_name_plural": "Special Pricing",
                "ordering": ["-date_created"],
                "abstract": False,
                "unique_together": {("service", "client_customer")},
            },
        ),
    ]
