# Generated by Django 4.2.7 on 2025-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0009_disbursement"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
