# Generated by Django 4.2.7 on 2025-09-08 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounting",
            "0010_alter_paymentmethod_options_servicestandardpricing_and_more",
        ),
        ("accounting", "0010_payment_description"),
    ]

    operations = []
