# Generated by Django 4.2.7 on 2025-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0010_paymentmethod_created_by_paymentmethod_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salescategory",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="salescategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
