# Generated by Django 4.2.7 on 2025-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0010_payment_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
        migrations.AddField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="currency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
