# Generated by Django 4.2.7 on 2025-12-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0011_alter_salescategory_code_alter_salescategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesitem",
            name="item_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
