# Generated by Django 4.2.7 on 2025-09-10 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0011_alter_paymentmethod_options_currency_symbol_and_more"),
        ("accounting", "0011_merge_20250908_1509"),
    ]

    operations = []
