# Generated by Django 4.2.7 on 2025-09-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_initial"),
        ("accounting", "0012_merge_20250910_1504"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicespecialpricing",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Service Special Pricing",
                "verbose_name_plural": "Services Special Pricing",
            },
        ),
        migrations.AlterModelOptions(
            name="servicestandardpricing",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Service Standard Pricing",
                "verbose_name_plural": "Services Standard Pricing",
            },
        ),
        migrations.AlterField(
            model_name="servicespecialpricing",
            name="client_customer",
            field=models.ForeignKey(
                help_text="The specific client this special pricing is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="special_pricing",
                to="clients.client",
            ),
        ),
    ]
