# Generated by Django 4.2.7 on 2025-12-10 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0012_alter_salesitem_item_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bankaccount",
            options={
                "ordering": ["cashbook_id", "bank_name"],
                "verbose_name": "Bank Account",
                "verbose_name_plural": "Bank Accounts",
            },
        ),
        migrations.RemoveField(
            model_name="bankaccount",
            name="account_number",
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="back_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="cashbook_id",
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="gl_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="opening_balance_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
