# Generated by Django 4.2.7 on 2025-10-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0013_alter_servicespecialpricing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashbook",
            options={"verbose_name": "Cash Book", "verbose_name_plural": "Cash Books"},
        ),
        migrations.AlterModelOptions(
            name="cashbookentry",
            options={
                "verbose_name": "Cashbook Entry",
                "verbose_name_plural": "Cashbook Entries",
            },
        ),
        migrations.AlterModelOptions(
            name="cashsale",
            options={"verbose_name": "Cash Sale", "verbose_name_plural": "Cash Sales"},
        ),
        migrations.AlterModelOptions(
            name="creditnote",
            options={
                "verbose_name": "Credit Note",
                "verbose_name_plural": "Credit Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies"},
        ),
        migrations.AlterModelOptions(
            name="currencyrate",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "Currency Rate",
                "verbose_name_plural": "Currency Rates",
            },
        ),
        migrations.AlterModelOptions(
            name="generalledgeraccount",
            options={
                "verbose_name": "General Ledger Account",
                "verbose_name_plural": "General Ledger Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="ledgertransaction",
            options={
                "verbose_name": "Ledger Transaction",
                "verbose_name_plural": "Ledger Transactions",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Payment", "verbose_name_plural": "Payments"},
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="salescategory",
            options={
                "verbose_name": "Sales Category",
                "verbose_name_plural": "Sales Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="salesitem",
            options={
                "verbose_name": "Sales Item",
                "verbose_name_plural": "Sales Items",
            },
        ),
        migrations.AlterModelOptions(
            name="transactiontype",
            options={
                "verbose_name": "Transaction Type",
                "verbose_name_plural": "Transaction Types",
            },
        ),
        migrations.AlterModelOptions(
            name="vatsetting",
            options={
                "verbose_name": "VAT Setting",
                "verbose_name_plural": "VAT Settings",
            },
        ),
    ]
