# Generated by Django 4.2.7 on 2025-12-11 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0013_alter_bankaccount_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="back_account_number",
            new_name="bank_account_number",
        ),
    ]
