# Generated by Django 4.2.7 on 2025-10-06 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0013_alter_servicespecialpricing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountsector",
            options={
                "ordering": ["code"],
                "verbose_name": "Account Sector",
                "verbose_name_plural": "Account Sectors",
            },
        ),
        migrations.AlterModelOptions(
            name="salesaccount",
            options={
                "ordering": ["account_number"],
                "verbose_name": "Sales Account",
                "verbose_name_plural": "Sales Accounts",
            },
        ),
    ]
