# Generated by Django 4.2.7 on 2025-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0013_alter_servicespecialpricing_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_invoiced",
            field=models.BooleanField(default=False),
        ),
    ]
