# Generated by Django 4.2.7 on 2025-12-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounting",
            "0014_rename_back_account_number_bankaccount_bank_account_number",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="gl_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="accounting.generalledgeraccount",
            ),
        ),
    ]
