# Generated by Django 4.2.7 on 2025-10-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_companyprofile_account_number"),
        ("individuals", "0008_employmentdetail_industry"),
        (
            "accounting",
            "0015_alter_salescategory_options_salescategory_created_by_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("is_individual", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.company",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="individuals.individual",
                    ),
                ),
            ],
            options={
                "verbose_name": "base model",
                "verbose_name_plural": "base models",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="accounting.customer",
            ),
        ),
    ]
