# Generated by Django 4.2.7 on 2025-10-30 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0016_customer_alter_invoice_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cashbook",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounting.cashbook",
            ),
        ),
    ]
