# Generated by Django 4.2.7 on 2025-10-27 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounting",
            "0014_alter_cashbook_options_alter_cashbookentry_options_and_more",
        ),
        ("accounting", "0016_customer_alter_invoice_customer"),
    ]

    operations = []
