# Generated by Django 4.2.7 on 2025-10-28 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0014_alter_accountsector_options_and_more"),
        ("accounting", "0016_customer_alter_invoice_customer"),
    ]

    operations = []
