# Generated by Django 4.2.7 on 2025-10-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0017_merge_20251028_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalledgeraccount",
            name="is_secondary_currency",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="sales_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="accounting.generalledgeraccount",
            ),
        ),
        migrations.DeleteModel(
            name="SalesAccount",
        ),
    ]
