# Generated by Django 4.2.7 on 2025-10-27 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0017_merge_20251027_1024"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgertransaction",
            options={},
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "verbose_name": "payment method",
                "verbose_name_plural": "payment methods",
            },
        ),
    ]
