# Generated by Django 4.2.7 on 2025-10-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0019_alter_generalledgeraccount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalledgeraccount",
            name="account_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
