# Generated by Django 4.2.7 on 2025-10-29 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0018_alter_ledgertransaction_options_and_more"),
        ("accounting", "0020_alter_generalledgeraccount_account_name"),
    ]

    operations = []
