# Generated by Django 4.2.7 on 2025-10-30 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0017_payment_cashbook"),
        ("accounting", "0021_merge_20251029_1047"),
    ]

    operations = []
