# Generated by Django 4.2.7 on 2025-10-30 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0023_alter_cashsale_company_alter_creditnote_company_and_more"),
        ("accounting", "0022_merge_0017_payment_cashbook_0021_merge_20251029_1047"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditnote",
            name="company",
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="individual",
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="is_individual",
        ),
        migrations.AddField(
            model_name="creditnote",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.customer",
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="credit_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="document_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
