# Generated by Django 4.2.7 on 2025-11-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_alter_companyprofile_account_number"),
        ("accounting", "0022_merge_0017_payment_cashbook_0021_merge_20251029_1047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashsale",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.companybranch",
            ),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.companybranch",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.companybranch",
            ),
        ),
    ]
