# Generated by Django 4.2.7 on 2025-11-10 09:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0024_alter_creditnote_credit_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
