# Generated by Django 4.2.7 on 2025-11-03 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0024_remove_creditnote_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="credit_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
