# Generated by Django 4.2.7 on 2025-11-13 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0023_alter_cashsale_company_alter_creditnote_company_and_more"),
        ("accounting", "0025_creditnote_discount"),
    ]

    operations = []
