# Generated by Django 4.2.7 on 2025-11-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0026_creditnote_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vatsetting",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
