# Generated by Django 4.2.7 on 2025-07-19 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounting", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "service_name",
                    models.CharField(
                        help_text="The name of the service provided.",
                        max_length=55,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The user who last created or modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "db_table": "services",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name of the subscription period (e.g., 'Monthly', 'Annual').",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Short code for the period (e.g., 'M', 'A').",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "period_length_days",
                    models.IntegerField(
                        blank=True,
                        help_text="The duration of this subscription period in days (e.g., 30, 365).",
                        null=True,
                    ),
                ),
                (
                    "period_length_months",
                    models.IntegerField(
                        blank=True,
                        help_text="The duration of this subscription period in months (e.g., 1, 3, 12).",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The user who last created or modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription period",
                "verbose_name_plural": "subscription periods",
                "db_table": "subscription_periods",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the subscribing entity (Individual or Company)."
                    ),
                ),
                (
                    "is_activated",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this subscription is currently active and usable.",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        help_text="The date and time when the subscription became active.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the subscription is scheduled to end.",
                        null=True,
                    ),
                ),
                (
                    "subscription_class",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("COMPANY", "Company"),
                            ("COMBINED", "Combined"),
                        ],
                        help_text="The classification of the subscriber (e.g., Individual, Company).",
                        max_length=10,
                    ),
                ),
                (
                    "total_slots",
                    models.IntegerField(
                        default=1,
                        help_text="The total number of lease slots this subscription provides for RentSafe service.",
                    ),
                ),
                (
                    "used_slots",
                    models.IntegerField(
                        default=0,
                        help_text="The number of lease slots currently in use by active leases under this subscription.",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The total amount paid for the entire subscription period.",
                        max_digits=12,
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The equivalent monthly cost of the subscription, if applicable.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="The type of entity subscribing (Individual or Company).",
                        limit_choices_to=models.Q(
                            models.Q(
                                ("app_label", "individuals"), ("model", "individual")
                            ),
                            models.Q(
                                ("app_label", "companies"), ("model", "companybranch")
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="The currency in which this subscription is paid.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions_currency",
                        to="accounting.currency",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="The primary method of payment for this subscription.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions_payment_method",
                        to="accounting.paymentmethod",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="The billing period for this subscription (e.g., Monthly, Annually).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionperiod",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="The service provided by this subscription (e.g., RentSafe).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.services",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="The user who last created or modified this record.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "db_table": "subscriptions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(("used_slots__lte", models.F("total_slots"))),
                name="used_lte_total_slots",
            ),
        ),
    ]
