# Generated by Django 4.2.7 on 2025-08-18 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subscriptionperiod",
            name="user",
        ),
    ]
