# Generated by Django 4.2.7 on 2025-07-09 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="services",
            table="services",
        ),
        migrations.AlterModelTable(
            name="subscriptionperiod",
            table="subscription_periods",
        ),
    ]
