# Generated by Django 4.2.7 on 2025-08-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_initial"),
        (
            "subscriptions",
            "0003_remove_services_user_remove_subscription_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-date_created"],
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
            },
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="object_id",
        ),
        migrations.AddField(
            model_name="services",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Short code for the product).",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="clients.client",
            ),
            preserve_default=False,
        ),
    ]
