# Generated by Django 4.2.7 on 2025-09-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="used_slots",
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_id",
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_class",
            field=models.CharField(
                choices=[("COMBINED", "Combined")],
                default="COMBINED",
                help_text="The classification of the subscriber (e.g., Individual, Company).",
                max_length=10,
            ),
        ),
    ]
