# Generated by Django 4.2.7 on 2025-11-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guarantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "guarantee_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The maximum amount guaranteed by this guarantor, if specified.",
                        max_digits=12,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "guarantor",
                "verbose_name_plural": "guarantors",
                "db_table": "guarantor",
            },
        ),
        migrations.CreateModel(
            name="Landlord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("landlord_name", models.CharField(max_length=255)),
                (
                    "landlord_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("company", "Company")],
                        max_length=100,
                    ),
                ),
                (
                    "landlord_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Landlord",
                "verbose_name_plural": "Landlords",
                "db_table": "landlord",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="LandlordOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "lease_id",
                    models.CharField(
                        blank=True,
                        help_text="The ID of the lease associated with this opening balance.",
                        max_length=255,
                        null=True,
                        verbose_name="Lease ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The amount of the opening balance owed.",
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The commission rate applied to the balance.",
                        max_digits=5,
                        verbose_name="Commission Percentage",
                    ),
                ),
                (
                    "operating_costs_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if operating costs are included in the amount.",
                        verbose_name="Operating Costs Inclusive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landlord Opening Balance",
                "verbose_name_plural": "Landlord Opening Balances",
                "db_table": "landlord_opening_balance",
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "lease_id",
                    models.CharField(
                        help_text="Unique identifier for the lease (e.g., LSE-001).",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="The date when the lease officially starts.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="The date when the lease is scheduled to end. Can be null for open-ended leases.",
                        null=True,
                    ),
                ),
                (
                    "signed_date",
                    models.DateField(
                        blank=True,
                        help_text="The actual date the lease agreement was signed.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("ACTIVE", "Active"),
                            ("TERMINATED", "Terminated"),
                            ("EXPIRED", "Expired"),
                            ("RENEWED", "Renewed"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        help_text="Current operational status of the lease.",
                        max_length=20,
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("HALF_YEARLY", "Half-Yearly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        help_text="The default payment frequency for recurring charges.",
                        max_length=20,
                    ),
                ),
                (
                    "due_day_of_month",
                    models.SmallIntegerField(
                        default=25,
                        help_text="The day of the month when recurring charges are typically due (1-31).",
                    ),
                ),
                (
                    "grace_period_days",
                    models.SmallIntegerField(
                        default=7,
                        help_text="Number of days after the due date before a payment is considered late.",
                    ),
                ),
                (
                    "includes_utilities",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if basic utilities are included in the overall rent.",
                    ),
                ),
                (
                    "utilities_details",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of utilities included or managed separately.",
                        null=True,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        help_text="Optional bank account number or reference for tenant payments.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_rent_variable",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the rent amount is variable.",
                    ),
                ),
            ],
            options={
                "verbose_name": "lease",
                "verbose_name_plural": "leases",
                "ordering": ["-start_date", "lease_id"],
            },
        ),
        migrations.CreateModel(
            name="LeaseCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("UTILITY", "Utility"),
                            ("SERVICE_FEE", "Service Fee"),
                            ("LATE_FEE", "Late Fee"),
                            ("DEPOSIT", "Deposit"),
                            ("DISCOUNT", "Discount"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="A brief description of the charge (e.g., 'Monthly Rent - Jan 2024', 'Water Bill').",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The monetary amount of the charge. Use negative for discounts.",
                        max_digits=12,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "One-time"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="MONTHLY",
                        help_text="How often this charge recurs.",
                        max_length=20,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="The date from which this charge becomes effective.",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="The date this charge stops being applied (e.g., for rent increases/discounts).",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if this charge is currently active and should be applied.",
                    ),
                ),
                (
                    "vat_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the charge amount includes VAT.",
                    ),
                ),
            ],
            options={
                "verbose_name": "lease charge",
                "verbose_name_plural": "lease charges",
                "db_table": "lease_charge",
                "ordering": ["lease", "effective_date", "charge_type"],
            },
        ),
        migrations.CreateModel(
            name="LeaseDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deposit_date", models.DateField(blank=True, null=True)),
                (
                    "deposit_holder",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("landlord", "Landlord"),
                            ("tenant", "Tenant"),
                        ],
                        default="agent",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "lease deposit",
                "verbose_name_plural": "lease deposits",
                "db_table": "lease_deposit",
            },
        ),
        migrations.CreateModel(
            name="LeaseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("LEASE_CREATED", "Lease Created"),
                            ("LEASE_UPDATED", "Lease Updated"),
                            ("TENANT_ADDED", "Tenant Added"),
                            ("TENANT_REMOVED", "Tenant Removed"),
                            ("PRIMARY_TENANT_CHANGED", "Primary Tenant Changed"),
                            ("LEASE_STATUS_CHANGED", "Lease Status Changed"),
                            ("LEASE_TERMINATED", "Lease Terminated"),
                            ("LEASE_RENEWED", "Lease Renewed"),
                            ("CHARGE_ADDED", "Charge Added"),
                            ("CHARGE_UPDATED", "Charge Updated"),
                            ("CHARGE_REMOVED", "Charge Removed"),
                            ("DEPOSIT_UPDATED", "Deposit Updated"),
                            ("OTHER", "Other"),
                        ],
                        help_text="The type of event being logged.",
                        max_length=50,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the event occurred.",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        help_text="JSON field to store detailed changes or relevant data, including core lease identifiers.",
                        null=True,
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="The ID of the related object.", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "lease log",
                "verbose_name_plural": "lease logs",
                "db_table": "lease_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LeaseOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "current_month_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance for the current month.",
                        max_digits=12,
                        verbose_name="Current Month Balance",
                    ),
                ),
                (
                    "one_month_back_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance from one month ago.",
                        max_digits=12,
                        verbose_name="1-Month Back Balance",
                    ),
                ),
                (
                    "two_months_back_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance from two months ago.",
                        max_digits=12,
                        verbose_name="2-Months Back Balance",
                    ),
                ),
                (
                    "three_months_back_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance from three months ago.",
                        max_digits=12,
                        verbose_name="3-Months Back Balance",
                    ),
                ),
                (
                    "three_months_plus_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance older than three months.",
                        max_digits=12,
                        verbose_name="3-Months+ Balance",
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total outstanding balance (sum of all aged balances).",
                        max_digits=12,
                        verbose_name="Total Outstanding Balance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease Opening Balance",
                "verbose_name_plural": "Lease Opening Balances",
                "db_table": "lease_opening_balance",
            },
        ),
        migrations.CreateModel(
            name="LeaseTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(
                                ("app_label", "individuals"), ("model", "individual")
                            ),
                            models.Q(
                                ("app_label", "companies"), ("model", "companybranch")
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "lease tenant",
                "verbose_name_plural": "lease tenants",
                "db_table": "lease_tenant",
            },
        ),
        migrations.CreateModel(
            name="LeaseTermination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("termination_date", models.DateField()),
                (
                    "reason",
                    models.TextField(
                        help_text="Detailed reason for the lease termination."
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes related to the termination.",
                        null=True,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="termination",
                        to="leases.lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "lease termination",
                "verbose_name_plural": "lease terminations",
                "db_table": "lease_termination",
            },
        ),
        migrations.CreateModel(
            name="LeaseTenantAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("is_primary_tenant", models.BooleanField(default=False)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leases.lease"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leases.leasetenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease Tenant Association",
                "verbose_name_plural": "Lease Tenant Associations",
            },
        ),
    ]
