# Generated by Django 4.2.7 on 2025-11-19 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("properties", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0002_initial"),
        ("leases", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaseopeningbalance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaseopeningbalance",
            name="lease",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opening_balance",
                to="leases.lease",
                verbose_name="Lease",
            ),
        ),
        migrations.AddField(
            model_name="leaseopeningbalance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaselog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The content type of the related object (e.g., LeaseTenant).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="leaselog",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                help_text="The lease associated with this log entry. Set to NULL if the lease is deleted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="leaselog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who performed the action, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leasedeposit",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounting.currency"
            ),
        ),
        migrations.AddField(
            model_name="leasedeposit",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposits",
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="leasecharge",
            name="currency",
            field=models.ForeignKey(
                help_text="The currency for this specific charge.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lease_charges",
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="leasecharge",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="currency",
            field=models.ForeignKey(
                help_text="The primary currency in which the lease payments and charges are accounted for.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases_as_primary_currency",
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="guarantor",
            field=models.ForeignKey(
                blank=True,
                help_text="The guarantor responsible for financial obligations under this lease.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leases.guarantor",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                help_text="The landlord responsible for this lease.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_leases",
                to="leases.landlord",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="lease_tenants",
            field=models.ManyToManyField(
                blank=True,
                related_name="leases",
                through="leases.LeaseTenantAssociation",
                to="leases.leasetenant",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="managing_client",
            field=models.ForeignKey(
                blank=True,
                help_text="The client responsible for managing this lease.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_leases",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="unit",
            field=models.ForeignKey(
                help_text="The property unit being leased.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="properties.unit",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landlordopeningbalance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landlordopeningbalance",
            name="debtor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlord_opening_balances",
                to="clients.client",
                verbose_name="Debtor",
            ),
        ),
        migrations.AddField(
            model_name="landlordopeningbalance",
            name="landlord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opening_balances",
                to="leases.landlord",
                verbose_name="Landlord",
            ),
        ),
        migrations.AddField(
            model_name="landlordopeningbalance",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landlord",
            name="properties",
            field=models.ManyToManyField(
                related_name="landlords", to="properties.property"
            ),
        ),
        migrations.AddField(
            model_name="guarantor",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leasetenantassociation",
            unique_together={("lease", "tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="leasetenant",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="leaseopeningbalance",
            unique_together={("lease",)},
        ),
        migrations.AlterUniqueTogether(
            name="guarantor",
            unique_together={("content_type", "object_id")},
        ),
    ]
