# Generated by Django 4.2.7 on 2025-07-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0002_initial"),
        ("properties", "0002_initial"),
        ("leases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasetermination",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leasetenant",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="leasetenant",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_tenants",
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="leasetenant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaselog",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="The content type of the related object (e.g., LeaseTenant).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="leaselog",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                help_text="The lease associated with this log entry. Set to NULL if the lease is deleted.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="leaselog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who performed the action, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leasecharge",
            name="currency",
            field=models.ForeignKey(
                help_text="The currency for this specific charge.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lease_charges",
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="leasecharge",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charges",
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="leasecharge",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="currency",
            field=models.ForeignKey(
                help_text="The primary currency in which the lease payments and charges are accounted for.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases_as_primary_currency",
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="guarantor",
            field=models.ForeignKey(
                blank=True,
                help_text="The guarantor responsible for financial obligations under this lease.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leases.guarantor",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="landlord",
            field=models.ForeignKey(
                help_text="The landlord responsible for this lease.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_leases",
                to="leases.landlord",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="unit",
            field=models.ForeignKey(
                help_text="The property unit being leased.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="properties.unit",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="landlord",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="landlord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guarantor",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "individuals"), ("model", "individual")),
                    models.Q(("app_label", "companies"), ("model", "companybranch")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="guarantor",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leasetenant",
            unique_together={("lease", "content_type", "object_id")},
        ),
        migrations.AlterUniqueTogether(
            name="guarantor",
            unique_together={("content_type", "object_id")},
        ),
    ]
