# Generated by Django 4.2.7 on 2025-07-19 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="landlord",
            table=None,
        ),
    ]
