# Generated by Django 4.2.7 on 2025-08-18 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_remove_property_user_remove_propertytype_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leases", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guarantor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="landlord",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="landlord",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="landlord",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leasecharge",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leasetenant",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leasetermination",
            name="user",
        ),
        migrations.AddField(
            model_name="landlord",
            name="landlord_name",
            field=models.CharField(default="n", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landlord",
            name="landlord_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("company", "Company")],
                default="individual",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landlord",
            name="property",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landlords",
                to="properties.property",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lease",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
