# Generated by Django 4.2.7 on 2025-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_remove_unit_monthly_rent"),
        ("leases", "0003_remove_guarantor_user_remove_landlord_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landlord",
            name="property",
        ),
        migrations.AddField(
            model_name="landlord",
            name="landlord_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="landlord",
            name="properties",
            field=models.ManyToManyField(
                related_name="landlords", to="properties.property"
            ),
        ),
    ]
