# Generated by Django 4.2.7 on 2025-08-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0004_remove_landlord_property_landlord_landlord_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                help_text="The landlord responsible for this lease.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_leases",
                to="leases.landlord",
            ),
        ),
    ]
