# Generated by Django 4.2.7 on 2025-08-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0005_alter_lease_landlord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasecharge",
            name="charge_type",
            field=models.CharField(
                choices=[
                    ("RENT", "Rent"),
                    ("UTILITY", "Utility"),
                    ("SERVICE_FEE", "Service Fee"),
                    ("LATE_FEE", "Late Fee"),
                    ("DEPOSIT", "Deposit"),
                    ("DISCOUNT", "Discount"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
