# Generated by Django 4.2.7 on 2025-08-26 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leases", "0006_alter_leasecharge_charge_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandlordOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The amount of the opening balance owed.",
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The commission rate applied to the balance.",
                        max_digits=5,
                        verbose_name="Commission Percentage",
                    ),
                ),
                (
                    "operating_costs_inclusive",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if operating costs are included in the amount.",
                        verbose_name="Operating Costs Inclusive",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "debtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlord_opening_balances",
                        to="clients.client",
                        verbose_name="Debtor",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="leases.landlord",
                        verbose_name="Landlord",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Landlord Opening Balance",
                "verbose_name_plural": "Landlord Opening Balances",
                "db_table": "landlord_opening_balance",
            },
        ),
        migrations.CreateModel(
            name="LeaseOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "current_month_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance for the current month.",
                        max_digits=12,
                        verbose_name="Current Month Balance",
                    ),
                ),
                (
                    "one_month_back_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance from one month ago.",
                        max_digits=12,
                        verbose_name="1-Month Back Balance",
                    ),
                ),
                (
                    "two_months_back_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance from two months ago.",
                        max_digits=12,
                        verbose_name="2-Months Back Balance",
                    ),
                ),
                (
                    "three_months_back_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance from three months ago.",
                        max_digits=12,
                        verbose_name="3-Months Back Balance",
                    ),
                ),
                (
                    "three_months_plus_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Outstanding balance older than three months.",
                        max_digits=12,
                        verbose_name="3-Months+ Balance",
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total outstanding balance (sum of all aged balances).",
                        max_digits=12,
                        verbose_name="Total Outstanding Balance",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balance",
                        to="leases.lease",
                        verbose_name="Lease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease Opening Balance",
                "verbose_name_plural": "Lease Opening Balances",
                "db_table": "lease_opening_balance",
                "unique_together": {("lease",)},
            },
        ),
    ]
