# Generated by Django 4.2.7 on 2025-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0007_landlordopeningbalance_leaseopeningbalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordopeningbalance",
            name="lease_id",
            field=models.CharField(
                blank=True,
                help_text="The ID of the lease associated with this opening balance.",
                max_length=255,
                null=True,
                verbose_name="Lease ID",
            ),
        ),
    ]
