# Generated by Django 4.2.7 on 2025-08-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0004_alter_invoice_lease"),
        ("leases", "0008_landlordopeningbalance_lease_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="is_rent_variable",
            field=models.BooleanField(
                default=False, help_text="Indicates if the rent amount is variable."
            ),
        ),
        migrations.CreateModel(
            name="LeaseDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("deposit_date", models.DateField(blank=True, null=True)),
                (
                    "deposit_holder",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("landlord", "Landlord"),
                            ("tenant", "Tenant"),
                        ],
                        default="agent",
                        max_length=255,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounting.currency",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposits",
                        to="leases.lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "lease deposit",
                "verbose_name_plural": "lease deposits",
                "db_table": "lease_deposit",
            },
        ),
    ]
