# Generated by Django 4.2.7 on 2025-08-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0009_lease_is_rent_variable_leasedeposit"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasecharge",
            name="vat_inclusive",
            field=models.BooleanField(
                default=False, help_text="Indicates if the charge amount includes VAT."
            ),
        ),
    ]
