# Generated by Django 4.2.7 on 2025-08-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0010_leasecharge_vat_inclusive"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lease",
            name="deposit_amount",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="deposit_period",
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("ACTIVE", "Active"),
                    ("TERMINATED", "Terminated"),
                    ("EXPIRED", "Expired"),
                    ("RENEWED", "Renewed"),
                    ("SUSPENDED", "Suspended"),
                ],
                default="ACTIVE",
                help_text="Current operational status of the lease.",
                max_length=20,
            ),
        ),
    ]
