# Generated by Django 4.2.7 on 2025-09-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_initial"),
        ("leases", "0011_remove_lease_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="managing_client",
            field=models.ForeignKey(
                blank=True,
                help_text="The client responsible for managing this lease.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="managed_leases",
                to="clients.client",
            ),
        ),
    ]
