# Generated by Django 4.2.7 on 2025-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("leases", "0012_lease_managing_client"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leasetenant",
            unique_together={("content_type", "object_id")},
        ),

        migrations.RemoveField(
            model_name="leasetenant",
            name="lease",
        ),
    ]
