# Generated by Django 4.2.7 on 2025-09-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0013_alter_leasetenant_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leasetenant",
            name="is_primary_tenant",
        ),
        migrations.CreateModel(
            name="LeaseTenantAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary_tenant", models.BooleanField(default=False)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leases.lease"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leases.leasetenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease Tenant Association",
                "verbose_name_plural": "Lease Tenant Associations",
                "unique_together": {("lease", "tenant")},
            },
        ),
        migrations.AddField(
            model_name="lease",
            name="lease_tenants",
            field=models.ManyToManyField(
                blank=True,
                related_name="leases",
                through="leases.LeaseTenantAssociation",
                to="leases.leasetenant",
            ),
        ),
        
    ]
