# Generated by Django 4.2.7 on 2025-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0014_remove_leasetenant_is_primary_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasetenantassociation",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="leasetenantassociation",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
