# Generated by Django 4.2.7 on 2025-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0015_leasetenantassociation_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("HALF_YEARLY", "Half-Yearly"),
                    ("ANNUALLY", "Annually"),
                ],
                default="MONTHLY",
                help_text="The default payment frequency for recurring charges.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leasecharge",
            name="effective_date",
            field=models.DateField(
                auto_now_add=True,
                help_text="The date from which this charge becomes effective.",
                null=True,
            ),
        ),
    ]
