# Generated by Django 4.2.7 on 2025-07-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical Address"),
                            ("postal", "Postal Address"),
                            ("billing", "Billing Address"),
                            ("work", "Work Address"),
                            ("other", "Other"),
                        ],
                        default="physical",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary address of its type for the linked object?",
                    ),
                ),
                (
                    "street_address",
                    models.CharField(
                        blank=True,
                        help_text="Street name, house/building number",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "line_2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, suite, or unit number",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=3)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("dial_code", models.CharField(max_length=5)),
                ("currency_code", models.CharField(max_length=3)),
                ("currency_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id", "Identification"),
                            ("proof_of_address", "Proof of Address"),
                            ("contract", "Contract"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("description", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                ("is_private", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("approved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "provinces",
            },
        ),
        migrations.CreateModel(
            name="Suburb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suburbs",
                        to="common.city",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "suburbs",
            },
        ),
    ]
