# Generated by Django 4.2.7 on 2025-08-18 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="user",
        ),
        migrations.RemoveField(
            model_name="city",
            name="user",
        ),
        migrations.RemoveField(
            model_name="country",
            name="user",
        ),
        migrations.RemoveField(
            model_name="document",
            name="user",
        ),
        migrations.RemoveField(
            model_name="note",
            name="user",
        ),
        migrations.RemoveField(
            model_name="province",
            name="user",
        ),
        migrations.RemoveField(
            model_name="suburb",
            name="user",
        ),
    ]
