# Generated by Django 4.2.7 on 2025-07-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Maintenance Request",
                "verbose_name_plural": "Maintenance Requests",
                "ordering": ["-requested_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="A brief title for the maintenance schedule.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the maintenance to be done.",
                        null=True,
                        verbose_name="Details",
                    ),
                ),
                (
                    "tradesman",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tradesman"
                    ),
                ),
                (
                    "contractor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Contractor Company",
                    ),
                ),
                (
                    "required_materials",
                    models.TextField(
                        blank=True, null=True, verbose_name="Required Materials"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Responsible Person",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Reason"),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                            ("BI_ANNUALLY", "Bi-Annually"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Frequency",
                    ),
                ),
                (
                    "scheduled_day",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Scheduled Day (e.g., 'Monday', '15th')",
                    ),
                ),
                (
                    "month_frequency",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Month Frequency (e.g., Every 3 months)",
                    ),
                ),
                (
                    "tenant_landlord_contact",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tenant/Landlord Contact",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("tenant_comms_history", "Tenant Comms History"),
                            ("creditor_comms_history", "Creditor Comms History"),
                        ],
                        default="tenant_comms_history",
                        max_length=130,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Schedule",
                "verbose_name_plural": "Maintenance Schedules",
                "ordering": ["-date_created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="A brief title for the work schedule.",
                        max_length=255,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the work to be done.",
                        null=True,
                        verbose_name="Details",
                    ),
                ),
                (
                    "tradesman",
                    models.CharField(
                        blank=True,
                        help_text="Name/ID of the tradesman performing the work.",
                        max_length=255,
                        null=True,
                        verbose_name="Tradesman",
                    ),
                ),
                (
                    "contractor",
                    models.CharField(
                        blank=True,
                        help_text="Name/ID of the contractor company.",
                        max_length=255,
                        null=True,
                        verbose_name="Contractor Company",
                    ),
                ),
                (
                    "required_materials",
                    models.TextField(
                        blank=True, null=True, verbose_name="Required Materials"
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True,
                        help_text="Name/ID of the person responsible for overseeing the work.",
                        max_length=255,
                        null=True,
                        verbose_name="Responsible Person",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the scheduled work (e.g., 'Tenant request', 'Routine maintenance').",
                        null=True,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Scheduled Date"
                    ),
                ),
                (
                    "tenant_landlord_contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact person (tenant or landlord) related to this work.",
                        max_length=250,
                        null=True,
                        verbose_name="Tenant/Landlord Contact",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("tenant_comms_history", "Tenant Comms History"),
                            ("creditor_comms_history", "Creditor Comms History"),
                        ],
                        default="tenant_comms_history",
                        max_length=130,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        help_text="The lease associated with this work schedule, if property is leased.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_schedules",
                        to="leases.lease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Schedule",
                "verbose_name_plural": "Work Schedules",
                "ordering": ["scheduled_date", "status"],
                "abstract": False,
            },
        ),
    ]
