# Generated by Django 4.2.7 on 2025-07-09 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenancerequest",
            options={
                "ordering": ["-requested_date"],
                "verbose_name": "Maintenance Request",
                "verbose_name_plural": "Maintenance Requests",
            },
        ),
    ]
