# Generated by Django 4.2.7 on 2025-08-20 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "maintenance",
            "0003_maintenanceschedule_maintenance_number_industry_and_more",
        ),
        ("maintenance", "0003_remove_maintenancerequest_user_and_more"),
    ]

    operations = []
