# Generated by Django 4.2.7 on 2025-08-29 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0004_merge_20250820_0940"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"ordering": ["name"], "verbose_name": "Industries"},
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="industry",
            name="user",
        ),
    ]
