/*const ranking = [
  "JPY", // Weakest per unit
  "INR",
  "ZWL", 
  "ZAR",
  "CNY",
  "AUD",
  "CAD",
  "USD",
  "EUR",
  "GBP"  // Strongest per unit
];
const currencyOps: Record<string, string> = {};

ranking.forEach((from, i) => {
  ranking.forEach((to, j) => {
    const key = `${from}_${to}`;
    if (from === to) {
      currencyOps[key] = "none";
    } else if (i < j) {
      currencyOps[key] = "divide";   // weaker to stronger
    } else {
      currencyOps[key] = "multiply"; // stronger to weaker
    }
  });
});
 */
export const CURRENCY_OPERATIONS: Record<string, string> = {
  "JPY_JPY": "none",
  "JPY_INR": "divide",
  "JPY_ZWL": "divide",
  "JPY_ZAR": "divide",
  "JPY_CNY": "divide",
  "JPY_AUD": "divide",
  "JPY_CAD": "divide",
  "JPY_USD": "divide",
  "JPY_EUR": "divide",
  "JPY_GBP": "divide",
  "INR_JPY": "multiply",
  "INR_INR": "none",
  "INR_ZWL": "divide",
  "INR_ZAR": "divide",
  "INR_CNY": "divide",
  "INR_AUD": "divide",
  "INR_CAD": "divide",
  "INR_USD": "divide",
  "INR_EUR": "divide",
  "INR_GBP": "divide",
  "ZWL_JPY": "multiply",
  "ZWL_INR": "multiply",
  "ZWL_ZWL": "none",
  "ZWL_ZAR": "divide",
  "ZWL_CNY": "divide",
  "ZWL_AUD": "divide",
  "ZWL_CAD": "divide",
  "ZWL_USD": "divide",
  "ZWL_EUR": "divide",
  "ZWL_GBP": "divide",
  "ZAR_JPY": "multiply",
  "ZAR_INR": "multiply",
  "ZAR_ZWL": "multiply",
  "ZAR_ZAR": "none",
  "ZAR_CNY": "divide",
  "ZAR_AUD": "divide",
  "ZAR_CAD": "divide",
  "ZAR_USD": "divide",
  "ZAR_EUR": "divide",
  "ZAR_GBP": "divide",
  "CNY_JPY": "multiply",
  "CNY_INR": "multiply",
  "CNY_ZWL": "multiply",
  "CNY_ZAR": "multiply",
  "CNY_CNY": "none",
  "CNY_AUD": "divide",
  "CNY_CAD": "divide",
  "CNY_USD": "divide",
  "CNY_EUR": "divide",
  "CNY_GBP": "divide",
  "AUD_JPY": "multiply",
  "AUD_INR": "multiply",
  "AUD_ZWL": "multiply",
  "AUD_ZAR": "multiply",
  "AUD_CNY": "multiply",
  "AUD_AUD": "none",
  "AUD_CAD": "divide",
  "AUD_USD": "divide",
  "AUD_EUR": "divide",
  "AUD_GBP": "divide",
  "CAD_JPY": "multiply",
  "CAD_INR": "multiply",
  "CAD_ZWL": "multiply",
  "CAD_ZAR": "multiply",
  "CAD_CNY": "multiply",
  "CAD_AUD": "multiply",
  "CAD_CAD": "none",
  "CAD_USD": "divide",
  "CAD_EUR": "divide",
  "CAD_GBP": "divide",
  "USD_JPY": "multiply",
  "USD_INR": "multiply",
  "USD_ZWL": "multiply",
  "USD_ZAR": "multiply",
  "USD_CNY": "multiply",
  "USD_AUD": "multiply",
  "USD_CAD": "multiply",
  "USD_USD": "none",
  "USD_EUR": "divide",
  "USD_GBP": "divide",
  "EUR_JPY": "multiply",
  "EUR_INR": "multiply",
  "EUR_ZWL": "multiply",
  "EUR_ZAR": "multiply",
  "EUR_CNY": "multiply",
  "EUR_AUD": "multiply",
  "EUR_CAD": "multiply",
  "EUR_USD": "multiply",
  "EUR_EUR": "none",
  "EUR_GBP": "divide",
  "GBP_JPY": "multiply",
  "GBP_INR": "multiply",
  "GBP_ZWL": "multiply",
  "GBP_ZAR": "multiply",
  "GBP_CNY": "multiply",
  "GBP_AUD": "multiply",
  "GBP_CAD": "multiply",
  "GBP_USD": "multiply",
  "GBP_EUR": "multiply",
  "GBP_GBP": "none"
}; 
