# Generated by Django 5.0.6 on 2024-11-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_send_email',
            field=models.BooleanField(default=True),
        ),
    ]
