# Generated by Django 5.0.6 on 2025-01-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=250, unique=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('expiration_time', models.DateTimeField()),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('search_type', models.CharField(blank=True, max_length=250, null=True)),
                ('search_value', models.CharField(blank=True, max_length=250, null=True)),
                ('national_id', models.CharField(blank=True, max_length=250, null=True)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_reg', models.CharField(blank=True, max_length=250, null=True)),
                ('trading_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_address', models.CharField(blank=True, max_length=250, null=True)),
                ('company_telephone', models.CharField(blank=True, max_length=250, null=True)),
                ('company_mobile', models.CharField(blank=True, max_length=250, null=True)),
                ('company_email', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_monthly_amount', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_address', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_detail', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_start_date', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_end_date', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_currency', models.CharField(blank=True, max_length=250, null=True)),
                ('is_lease_variable', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_deposit', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_pay_limit', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_current_balance', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_last_month_balance', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_last_two_month_balance', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_last_three_month_balance', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_last_four_month_balance', models.CharField(blank=True, max_length=250, null=True)),
                ('guarantor_id', models.CharField(blank=True, max_length=250, null=True)),
                ('user_id', models.CharField(blank=True, max_length=250, null=True)),
                ('company_id', models.CharField(blank=True, max_length=250, null=True)),
                ('lease_receiver_company', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'chat_user_session',
            },
        ),
    ]
