# Generated by Django 4.2.7 on 2025-07-10 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("AGENT", "Agent"),
                            ("CLIENT", "Client"),
                            ("LANDLORD", "Landlord"),
                            ("INDIVIDUAL_USER", "Individual Profile User"),
                            ("COMPANY_USER", "Company Profile User"),
                        ],
                        default="CLIENT",
                        help_text="The role or type of the user in the system.",
                        max_length=20,
                    ),
                ),
                (
                    "client_object_id",
                    models.PositiveIntegerField(
                        help_text="The ID of the associated client entity."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="A unique display name for this client. Auto-generated if empty.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PENDING", "Pending Approval"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        help_text="The current status of the client in the system.",
                        max_length=20,
                    ),
                ),
                (
                    "external_client_id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        help_text="An optional external ID for this client (e.g., from a CRM).",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the client was created.",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the client was last modified.",
                    ),
                ),
                (
                    "client_content_type",
                    models.ForeignKey(
                        help_text="The type of the associated client entity (Individual or Company).",
                        limit_choices_to=models.Q(
                            models.Q(
                                ("app_label", "individuals"), ("model", "individual")
                            ),
                            models.Q(
                                ("app_label", "companies"), ("model", "companybranch")
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="client_profiles",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "client",
                "ordering": ["name"],
            },
        ),
    ]
