# Generated by Django 4.2.7 on 2025-07-10 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this client profile.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("client_content_type", "client_object_id")},
        ),
    ]
