# Generated by Django 5.0.6 on 2025-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tin_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
