# Generated by Django 5.0.6 on 2025-05-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicing',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
