# Generated by Django 5.0.6 on 2024-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commshistmessage',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communicationhistoryreminder',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='debtorintelligencenote',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
