# Generated by Django 5.0.6 on 2025-04-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0003_alter_subcsriptions_subscription_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tin_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
