# Generated by Django 5.0.6 on 2025-04-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0004_company_tin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_terminated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tin_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
