# Generated by Django 5.0.6 on 2025-04-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0005_lease_is_terminated_alter_company_tin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
