# Generated by Django 5.0.6 on 2025-05-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0006_alter_lease_is_terminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='landlord_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='landlord_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='reg_ID_Number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
