# Generated by Django 5.0.6 on 2025-05-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0002_invoicing_invoice_date'),
        ('rentsafe', '0006_alter_lease_is_terminated'),
    ]

    operations = [
    ]
