# Generated by Django 5.0.6 on 2025-05-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0007_alter_landlord_landlord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicing',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
