# Generated by Django 5.0.6 on 2025-05-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0002_lease_is_terminated_alter_company_tin_number'),
        ('rentsafe', '0007_merge_20250509_0852'),
    ]

    operations = [
    ]
