# Generated by Django 5.0.6 on 2026-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0008_invoicing_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasereceiptbreakdown',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
