# Generated by Django 5.0.6 on 2025-05-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0007_alter_landlord_landlord_id_and_more'),
        ('rentsafe', '0008_merge_20250515_0850'),
    ]

    operations = [
    ]
