# Generated by Django 5.0.6 on 2025-05-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0008_merge_20250515_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaseCurrencyRate',
        ),
    ]
