# Generated by Django 5.0.6 on 2025-05-16 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0009_delete_leasecurrencyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseCurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=255)),
                ('current_rate', models.FloatField(default=0, max_length=255)),
                ('base_currency', models.CharField(default='USD', max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
