# Generated by Django 5.0.6 on 2025-05-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0009_merge_20250519_1553'),
        ('rentsafe', '0010_leasecurrencyrate'),
    ]

    operations = [
    ]
