# Generated by Django 5.0.6 on 2025-05-29 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0008_invoicing_invoice_date'),
        ('rentsafe', '0011_merge_0009_merge_20250519_1553_0010_leasecurrencyrate'),
    ]

    operations = [
    ]
