# Generated by Django 5.0.6 on 2025-05-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentsafe', '0012_merge_20250529_1520'),
        ('rentsafe', '0012_merge_20250529_1559'),
    ]

    operations = [
    ]
