# Generated by Django 5.0.6 on 2025-06-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentsafe", "0014_companyprofile_area_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="current_address",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="address",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="address",
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="area_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="street_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="street_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="suburb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="area_code",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="street_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="street_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="individual",
            name="suburb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LeaseAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("street_number", models.CharField(max_length=255)),
                ("street_name", models.CharField(max_length=255)),
                ("suburb", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("province", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(max_length=255)),
                ("area_code", models.CharField(max_length=15)),
                (
                    "lease_id",
                    models.ForeignKey(
                        blank=True,
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lease_address",
                        to="rentsafe.lease",
                    ),
                ),
            ],
        ),
    ]
