export const industries = [
  'Agriculture',
  'Banking',
  'Construction',
  'Education',
  'Energy',
  'Entertainment',
  'Finance',
  'Food',
  'Health',
  'Hospitality',
  'Insurance',
  'Manufacturing',
  'Media',
  'Retail',
  'Technology',
  'Telecommunications',
  'Transportation',
  'Aviation',
  'Real Estate',
  'Other',
];

export const activeTrackableClientNavLinks = {
  DASHBOARD: 'DASHBOARD',

  SERVICES: 'SERVICES',
  SE_RENTSAFE: 'SE_RENTSAFE',

  DATA: 'DATA',
  DA_ADVERSEDATA: 'DA_ADVERSEDATA',

  ACCOUNTING: 'ACCOUNTING',

  AC_CUSTOMERS: 'AC_CUSTOMERS',
  AC_CU_INVOICING: 'AC_CU_INVOICING',
  AC_CU_RECEIPTS: 'AC_CU_RECEIPTS',
  AC_CU_CUSTOMERSTATEMENTS: 'AC_CU_CUSTOMERSTATEMENTS',

  AC_CREDITORS: 'AC_CREDITORS',
  AC_CR_DISBURSEMENTS: 'AC_CR_DISBURSEMENTS',
  AC_CR_CREDITORSTATEMENTS: 'AC_CR_CREDITORSTATEMENTS',

  AC_JOURNALS: 'AC_JOURNALS',
  AC_JO_DEBITJOURNALS: 'AC_JO_DEBITJOURNALS',
  AC_JO_CREDITJOURNALS: 'AC_JO_CREDITJOURNALS',

  AC_REPORTS: 'AC_REPORTS',
  AC_RE_COMMISSIONSTATEMENTS: 'AC_RE_COMMISSIONSTATEMENTS',

  ADMIN: 'ADMIN',
  AD_INTERNALUSERS: 'AD_INTERNALUSERS',

  PROFILE: 'PROFILE',
};

export const residentialInspectionChecklist = [
  {
    category: 'Exterior',
    items: [
      'Back Doors',
      'Deck, veranda, patio',
      'Doorbell Soffits and fascia',
      'Front Doors',
      'Garage Doors',
      'Garbage receptacle',
      'House number',
      'Mailbox',
      'Outdoor lights',
      'Paint and trim',
      'Parking',
      'Recycling receptacle',
      'Sidewalks',
      'Siding (brick/stone/cement)',
      'Traffic noise',
      'Windows',
    ],
    description: 'Are things loose, cracked, damaged, rotted, bug infested?',
  },
  {
    category: 'Roof',
    items: ['Chimney', 'Gutters and downspouts', 'Soffits and fascia'],
    description: 'When was it replaced last? Are there encroaching trees?',
  },
  {
    category: 'Garage',
    items: [
      'Ceiling',
      'Doors',
      'Floors',
      'Lights',
      'Storage',
      'Walls',
      'Windows',
    ],
    description: 'Is the garage door opener operating properly?',
  },
  {
    category: 'Yard',
    items: [
      'Drainage',
      'Fences and Gates',
      'Retaining Wall',
      'Shed',
      'Water Tanks',
      'Borehole',
      'Swimming Pool',
    ],
    description: 'Trees, shrubs and lawn dead, dying or bug infested?',
  },
  {
    category: 'Blockages',
    items: ['Carbon Monoxide Detector', 'Mantle', 'Soot', 'Tiles'],
    description: 'Any buildup inside? Damage where connected to roof?',
  },
  {
    category: 'Bathrooms',
    subCategories: ['Bathroom 1', 'Bathroom 2', 'Bathroom 3'],
    items: [
      'Baseboards',
      'Cabinets, shelves, & drawers',
      'Ceiling',
      'Counter',
      'Doors',
      'Floors',
      'Shower',
      'Lights',
      'Mirror',
      'Outlets and Switches',
      'Sink',
      'Toilet',
      'Towel Hook',
      'Trim',
      'Tub',
      'Walls',
      'Window',
    ],
    description:
      'Fixtures secure? Condition of tiles and calking? Leaks or water pressure issues? Mold? Drawers and cabinets working?',
  },
  {
    category: 'Bedrooms',
    subCategories: ['Bedroom 1', 'Bedroom 2', 'Bedroom 3'],
    items: [
      'Baseboards',
      'Ceiling',
      'Closet',
      'Doors',
      'Floors',
      'Lights',
      'Outlets and switches',
      'Trim',
      'Walls',
      'Windows',
    ],
    description:
      'Check ceilings for sloping and/or water damage. Are floors weak in places? Damaged windows or window screens?',
  },
  {
    category: 'Dining Room',
    items: [
      'Baseboards',
      'Ceiling',
      'Floors',
      'Lights',
      'Outlets and switches',
      'Trim',
      'Walls',
      'Windows',
    ],
    description: 'Wall damage? Sloping ceiling? Weak floors?',
  },
  {
    category: 'Lounge',
    items: [
      'Baseboards',
      'Ceiling',
      'Ceiling fAN',
      'Doors',
      'Floors',
      'Lights',
      'Outlets and switches',
      'Trim',
      'Walls',
      'Windows',
    ],
    description: 'Wall damage? Sloping ceiling? Weak floors?',
  },
  {
    category: 'Kitchen',
    items: [
      'Baseboards',
      'Shelves and Cupboard',
      'Ceiling',
      'Counter',
      'Dishwasher',
      'Floors',
      'Garbage Disposal',
      'Lights',
      'Outlets and switches',
      'Oven',
      'Refrigerator',
      'Sink',
      'Smoke Detectors',
      'Stove',
      'Trim',
      'Walls',
      'Windows',
    ],
    description: 'Leaking sink or appliances? Cabinet & drawer condition?',
  },
  {
    category: 'Pantry',
    items: [
      'Baseboards',
      'Ceiling',
      'Shelves and Cupboard',
      'Doors',
      'Floors',
      'Lights',
      'Outlets and switches',
      'Trim',
      'Walls',
      'Windows',
    ],
    description: 'Wall damage? Sloping ceiling? Weak floors?',
  },
  {
    category: 'Attic',
    items: ['Insulation', 'Ladder', 'Ventilation'],
    description: 'Leaks, water damage, mold? Sufficient insulation?',
  },
  {
    category: 'Hallways',
    items: [
      'Baseboards',
      'Ceiling',
      'Closets',
      'Floors',
      'Lights',
      'Outlets and switches',
      'Skylights',
      'Trim',
      'Walls',
    ],
    description: 'Wall damage? Sloping ceiling? Weak floors?',
  },
  {
    category: 'Basement',
    items: [
      'Baseboards',
      'Ceiling',
      'Doors',
      'Floors',
      'Foundation',
      'Lights',
      'Outlets and switches',
      'Stairs',
      'Storage',
      'Sump pump',
      'Trim',
      'Walls',
      'Washer and dryer',
      'Windows',
    ],
    description: 'Damp, musty or moldy? Beam damage? Bugs?',
  },
  {
    category: 'Stairs',
    items: ['Floors', 'Landing', 'Lights', 'Railing', 'Treads', 'Walls'],
    description: 'Weak stairs? Railings available and secure?',
  },
  {
    category: 'Utilities',
    items: [
      'Air conditioning',
      'Circuit Breakers',
      'Drainage',
      'Solar',
      'Gyser',
      'Main Electrical Panel',
      'Water Pressure',
    ],
    description: 'Functioning properly? Are they new or old?',
  },
  {
    category: 'Other',
    items: ['Asbestos', 'Odor', 'Wood-eating insects'],
    description: 'Smoke and carbon monoxide detectors in place?',
  },
];
