# Generated by Django 4.2.7 on 2026-01-21 13:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0015_alter_bankaccount_gl_account"),
        ("properties", "0002_initial"),
        ("leases", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustGeneralLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "account_number",
                    models.CharField(
                        help_text="Unique code for the trust GL account",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_contra_account", models.BooleanField(default=False)),
                ("is_system_account", models.BooleanField(default=False)),
                ("requires_cost_center", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "account_subtype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_gl_sub_accounts",
                        to="accounting.accountsubtype",
                    ),
                ),
                (
                    "account_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_gl_accounts",
                        to="accounting.accounttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust General Ledger",
                "verbose_name_plural": "Trust General Ledger",
                "ordering": ["account_number", "account_name"],
            },
        ),
        migrations.CreateModel(
            name="TrustInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, editable=False, max_length=30, unique=True
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("management_fee", "Management Fee Invoice"),
                            ("commission", "Commission Invoice"),
                            ("expense_recovery", "Expense Recovery Invoice"),
                            ("maintenance", "Maintenance Invoice"),
                            ("other", "Other Invoice"),
                        ],
                        default="management_fee",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("written_off", "Written Off"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "period_from",
                    models.DateField(
                        blank=True, help_text="Start of billing period", null=True
                    ),
                ),
                (
                    "period_to",
                    models.DateField(
                        blank=True, help_text="End of billing period", null=True
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("terms", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_trust_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_invoices",
                        to="accounting.currency",
                    ),
                ),
                (
                    "journal_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_invoice",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        help_text="The landlord or beneficiary being invoiced",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_invoices",
                        to="leases.landlord",
                    ),
                ),
                (
                    "property_reference",
                    models.ForeignKey(
                        help_text="Property or lease reference for this invoice",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="properties.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant associated with this invoice",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_invoices",
                        to="leases.leasetenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Invoice",
                "verbose_name_plural": "Trust Invoices",
                "ordering": ["-invoice_date", "-invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="TrustInvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "property_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="trust_accounting.trustinvoice",
                    ),
                ),
                (
                    "trust_gl_account",
                    models.ForeignKey(
                        help_text="Trust GL account for this charge",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_line_items",
                        to="trust_accounting.trustgeneralledger",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Invoice Line Item",
                "verbose_name_plural": "Trust Invoice Line Items",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "expense",
                    models.CharField(
                        help_text="Name of the property-related expense", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="GL account for property-related expenses",
                        limit_choices_to={"account_type__account_type": "expense"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_expenses",
                        to="accounting.generalledgeraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Expense Account",
                "verbose_name_plural": "Property Expense Accounts",
                "ordering": ["expense"],
            },
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(
                fields=["invoice_number"], name="trust_accou_invoice_92027d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(
                fields=["tenant", "invoice_date"], name="trust_accou_tenant__728fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(fields=["status"], name="trust_accou_status_15ed96_idx"),
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(
                fields=["invoice_type"], name="trust_accou_invoice_c382dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgeneralledger",
            index=models.Index(
                fields=["account_number"], name="trust_accou_account_79e7fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgeneralledger",
            index=models.Index(
                fields=["account_name"], name="trust_accou_account_127fd5_idx"
            ),
        ),
    ]
