# Generated by Django 4.2.7 on 2026-02-02 10:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leases", "0002_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the invoice type",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Type",
                "verbose_name_plural": "Invoice Types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TrustAccountingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "period_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_open", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_closed_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Period",
                "verbose_name_plural": "Accounting Periods",
                "ordering": ["financial_year", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="TrustAccountSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code_prefix", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Trust Account Subtype",
                "verbose_name_plural": "Trust Account Subtypes",
                "ordering": ["account_type", "code_prefix"],
            },
        ),
        migrations.CreateModel(
            name="TrustAccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=20, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                            ("contra_asset", "Contra Asset"),
                            ("contra_liability", "Contra Liability"),
                            ("contra_equity", "Contra Equity"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        blank=True,
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Account Type",
                "verbose_name_plural": "Trust Account Types",
                "ordering": ["account_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrustCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("currency_code", models.CharField(max_length=3, unique=True)),
                ("currency_name", models.CharField(max_length=50)),
                ("symbol", models.CharField(blank=True, max_length=10, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_base_currency", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Trust Currency",
                "verbose_name_plural": "Trust Currencies",
                "ordering": ["currency_code"],
            },
        ),
        migrations.CreateModel(
            name="TrustGeneralLedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("account_number", models.CharField(max_length=10)),
                ("account_name", models.CharField(max_length=255)),
                (
                    "account_class",
                    models.CharField(
                        choices=[
                            ("balance_sheet", "Balance Sheet"),
                            ("income_statement", "Income Statement"),
                        ],
                        default="balance_sheet",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_contra_account", models.BooleanField(default=False)),
                ("is_system_account", models.BooleanField(default=False)),
                ("requires_cost_center", models.BooleanField(default=False)),
                ("requires_tax", models.BooleanField(default=False)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "opening_balance_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("balance_last_updated", models.DateTimeField(auto_now=True)),
                (
                    "account_subtype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_accounts",
                        to="trust_accounting.trustaccountsubtype",
                    ),
                ),
                (
                    "account_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_gl_accounts",
                        to="trust_accounting.trustaccounttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_sub_accounts",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust General Ledger Account",
                "verbose_name_plural": "Trust General Ledger Accounts",
                "ordering": ["account_number"],
            },
        ),
        migrations.CreateModel(
            name="TrustInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, editable=False, max_length=30, unique=True
                    ),
                ),
                ("document_number", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("written_off", "Written Off"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("next_invoice_date", models.DateField(blank=True, null=True)),
                (
                    "invoice_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "period_from",
                    models.DateField(
                        blank=True, help_text="Start of billing period", null=True
                    ),
                ),
                (
                    "period_to",
                    models.DateField(
                        blank=True, help_text="End of billing period", null=True
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("is_taxed", models.BooleanField(default=False)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("terms", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_trust_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_invoices",
                        to="trust_accounting.trustcurrency",
                    ),
                ),
                (
                    "invoice_type",
                    models.ForeignKey(
                        help_text="Type of the trust invoice",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_invoices",
                        to="trust_accounting.invoicetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Invoice",
                "verbose_name_plural": "Trust Invoices",
                "ordering": ["-invoice_date", "-invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="TrustJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "entry_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("entry_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Journal"),
                            ("sales", "Sales Journal"),
                            ("purchase", "Purchase Journal"),
                            ("cash_receipts", "Cash Receipts Journal"),
                            ("cash_disbursements", "Cash Disbursements Journal"),
                            ("adjusting", "Adjusting Entry"),
                            ("closing", "Closing Entry"),
                            ("reversing", "Reversing Entry"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "accounting_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="trust_accounting.trustaccountingperiod",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_approved_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_entries",
                        to="trust_accounting.trustjournalentry",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_reviewed_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrustSalesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_subcategories",
                        to="trust_accounting.trustsalescategory",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Sales Category",
                "verbose_name_plural": "Trust Sales Categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TrustTaxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10)),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"account_type__account_type": "liability"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_tax_payable_types",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"account_type__account_type": "asset"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_tax_receivable_types",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Tax Type",
                "verbose_name_plural": "Trust Tax Types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TrustSalesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("item_code", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=255)),
                ("unit_name", models.CharField(max_length=50)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("track_inventory", models.BooleanField(default=False)),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_items",
                        to="trust_accounting.trustsalescategory",
                    ),
                ),
                (
                    "cost_of_sales_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"account_type__account_type": "expense"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_cost_sales_items",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trust_accounting.trustcurrency",
                    ),
                ),
                (
                    "income_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"account_type__account_type": "revenue"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_sales_items",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "inventory_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"account_type__account_type": "asset"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_inventory_items",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "tax_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trust_accounting.trusttaxtype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Sales Item",
                "verbose_name_plural": "Trust Sales Items",
                "ordering": ["item_code"],
            },
        ),
        migrations.CreateModel(
            name="TrustPropertyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "expense",
                    models.CharField(
                        help_text="Name of the property-related expense", max_length=255
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="GL account for property-related expenses",
                        limit_choices_to={"account_type__account_type": "expense"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_property_expenses",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Property Expense Account",
                "verbose_name_plural": "Trust Property Expense Accounts",
                "ordering": ["expense"],
            },
        ),
        migrations.CreateModel(
            name="TrustLedgerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="trust_accounting.trustjournalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Ledger Transaction",
                "verbose_name_plural": "Trust Ledger Transactions",
                "ordering": ["journal_entry__entry_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrustInvoiceLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="trust_accounting.trustinvoice",
                    ),
                ),
                (
                    "sales_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trust_accounting.trustsalesitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Invoice Line Item",
                "verbose_name_plural": "Trust Invoice Line Items",
            },
        ),
        migrations.AddField(
            model_name="trustinvoice",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_invoice",
                to="trust_accounting.trustjournalentry",
            ),
        ),
        migrations.AddField(
            model_name="trustinvoice",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                help_text="The landlord or beneficiary being invoiced",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trust_invoices",
                to="leases.landlord",
            ),
        ),
        migrations.AddField(
            model_name="trustinvoice",
            name="lease",
            field=models.ForeignKey(
                help_text="Lease reference for this invoice",
                on_delete=django.db.models.deletion.PROTECT,
                to="leases.lease",
            ),
        ),
        migrations.AddField(
            model_name="trustinvoice",
            name="original_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_invoices",
                to="trust_accounting.trustinvoice",
            ),
        ),
        migrations.AddField(
            model_name="trustinvoice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The tenant associated with this invoice",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trust_invoices",
                to="leases.leasetenant",
            ),
        ),
        migrations.AddField(
            model_name="trustinvoice",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TrustGeneralLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "account_number",
                    models.CharField(
                        help_text="Unique code for the trust GL account",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_contra_account", models.BooleanField(default=False)),
                ("is_system_account", models.BooleanField(default=False)),
                ("requires_cost_center", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "account_subtype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_gl_ledger_sub_accounts",
                        to="trust_accounting.trustaccountsubtype",
                    ),
                ),
                (
                    "account_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trust_gl_ledger_accounts",
                        to="trust_accounting.trustaccounttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust General Ledger",
                "verbose_name_plural": "Trust General Ledger",
                "ordering": ["account_number", "account_name"],
            },
        ),
        migrations.CreateModel(
            name="TrustFinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_closed_financial_years",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrustExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "effective_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "source",
                    models.CharField(default="Currency Settings", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_base_rates",
                        to="trust_accounting.trustcurrency",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_target_rates",
                        to="trust_accounting.trustcurrency",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Exchange Rate",
                "verbose_name_plural": "Trust Exchange Rates",
                "ordering": ["-effective_date", "base_currency", "target_currency"],
            },
        ),
        migrations.AddField(
            model_name="trustaccountsubtype",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_subtypes",
                to="trust_accounting.trustaccounttype",
            ),
        ),
        migrations.AddField(
            model_name="trustaccountsubtype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trustaccountsubtype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trustaccountingperiod",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="trust_accounting.trustfinancialyear",
            ),
        ),
        migrations.AddIndex(
            model_name="trustsalesitem",
            index=models.Index(
                fields=["item_code"], name="trust_accou_item_co_33c4d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustsalesitem",
            index=models.Index(
                fields=["category"], name="trust_accou_categor_aed970_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustsalesitem",
            index=models.Index(
                fields=["is_active"], name="trust_accou_is_acti_01a98b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustledgertransaction",
            index=models.Index(
                fields=["account", "journal_entry"],
                name="trust_accou_account_1e8022_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trustjournalentry",
            index=models.Index(
                fields=["entry_date"], name="trust_accou_entry_d_d22300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustjournalentry",
            index=models.Index(
                fields=["entry_type"], name="trust_accou_entry_t_34538c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustjournalentry",
            index=models.Index(
                fields=["is_posted"], name="trust_accou_is_post_24b0ad_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trustinvoicelineitem",
            unique_together={("invoice", "sales_item")},
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(
                fields=["invoice_number"], name="trust_accou_invoice_92027d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(
                fields=["tenant", "invoice_date"], name="trust_accou_tenant__728fdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(fields=["status"], name="trust_accou_status_15ed96_idx"),
        ),
        migrations.AddIndex(
            model_name="trustinvoice",
            index=models.Index(
                fields=["invoice_type"], name="trust_accou_invoice_be090c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgeneralledgeraccount",
            index=models.Index(
                fields=["account_number"], name="trust_accou_account_9e5e78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgeneralledgeraccount",
            index=models.Index(
                fields=["is_active"], name="trust_accou_is_acti_61d391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgeneralledger",
            index=models.Index(
                fields=["account_number"], name="trust_accou_account_79e7fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustgeneralledger",
            index=models.Index(
                fields=["account_name"], name="trust_accou_account_127fd5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trustfinancialyear",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="trust_end_date_after_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="trustaccountingperiod",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="trust_period_end_date_after_start_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trustaccountingperiod",
            unique_together={("financial_year", "period_number")},
        ),
    ]
