# Generated by Django 4.2.7 on 2026-01-27 09:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trust_accounting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustAccountingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "period_number",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_open", models.BooleanField(default=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_closed_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Accounting Period",
                "verbose_name_plural": "Accounting Periods",
                "ordering": ["financial_year", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="TrustJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "entry_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("entry_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Journal"),
                            ("sales", "Sales Journal"),
                            ("purchase", "Purchase Journal"),
                            ("cash_receipts", "Cash Receipts Journal"),
                            ("cash_disbursements", "Cash Disbursements Journal"),
                            ("adjusting", "Adjusting Entry"),
                            ("closing", "Closing Entry"),
                            ("reversing", "Reversing Entry"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("reviewed_date", models.DateTimeField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                (
                    "accounting_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entries",
                        to="trust_accounting.trustaccountingperiod",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_approved_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_entries",
                        to="trust_accounting.trustjournalentry",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_reviewed_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "ordering": ["-entry_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TrustFinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_closed_financial_years",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="trustaccountingperiod",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="trust_accounting.trustfinancialyear",
            ),
        ),
        migrations.AlterField(
            model_name="trustinvoice",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trust_invoice",
                to="trust_accounting.trustjournalentry",
            ),
        ),
        migrations.CreateModel(
            name="TrustLedgerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "debit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "credit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="trust_accounting.trustgeneralledgeraccount",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="trust_accounting.trustjournalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trust Ledger Transaction",
                "verbose_name_plural": "Trust Ledger Transactions",
                "ordering": ["journal_entry__entry_date", "id"],
                "indexes": [
                    models.Index(
                        fields=["account", "journal_entry"],
                        name="trust_accou_account_1e8022_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="trustjournalentry",
            index=models.Index(
                fields=["entry_date"], name="trust_accou_entry_d_d22300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustjournalentry",
            index=models.Index(
                fields=["entry_type"], name="trust_accou_entry_t_34538c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trustjournalentry",
            index=models.Index(
                fields=["is_posted"], name="trust_accou_is_post_24b0ad_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="trustfinancialyear",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="trust_end_date_after_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="trustaccountingperiod",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="trust_period_end_date_after_start_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trustaccountingperiod",
            unique_together={("financial_year", "period_number")},
        ),
    ]
