# Generated by Django 4.2.7 on 2026-02-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust_accounting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicetype",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="invoicetype",
            name="updated_by",
        ),
        migrations.RenameIndex(
            model_name="trustinvoice",
            new_name="trust_accou_invoice_c382dc_idx",
            old_name="trust_accou_invoice_be090c_idx",
        ),
        migrations.AlterField(
            model_name="trustinvoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("fiscal", "Fiscal Invoice"),
                    ("proforma", "Proforma Invoice"),
                    ("recurring", "Recurring Invoice"),
                ],
                default="fiscal",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="InvoiceType",
        ),
    ]
