# Generated by Django 4.2.7 on 2026-02-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trust_accounting", "0002_remove_invoicetype_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trustinvoice",
            name="is_invoiced",
            field=models.BooleanField(default=False),
        ),
    ]
