# Generated by Django 4.2.7 on 2026-01-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0002_initial"),
        ("trust_accounting", "0002_trustaccountingperiod_trustjournalentry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trustinvoice",
            name="landlord",
            field=models.ForeignKey(
                blank=True,
                help_text="The landlord or beneficiary being invoiced",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trust_invoices",
                to="leases.landlord",
            ),
        ),
        migrations.AlterField(
            model_name="trustinvoice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="The tenant associated with this invoice",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trust_invoices",
                to="leases.leasetenant",
            ),
        ),
    ]
