# Generated by Django 5.0.6 on 2025-06-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencyrate",
            name="updated_at",
        ),
    ]
