# Generated by Django 5.0.6 on 2025-06-18 09:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_remove_currencyrate_updated_at"),
        ("rentsafe", "0013_merge_20250529_1608"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashsale",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="cashsale",
            name="amount_received",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="cashbook",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashsales_cashbook",
                to="accounting.cashbook",
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rentsafe.company",
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.currency",
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="document_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="individual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rentsafe.individual",
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="invoice_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="is_individual",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="payment_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="total_excluding_vat",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cashsale",
            name="vat_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
