# Generated by Django 5.0.6 on 2025-03-11 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_delete_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaccount',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salescategory',
            name='code',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salescategory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatsetting',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cashbookentry',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashsale',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cashsale',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salesaccount',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salescategory',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vatsetting',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
