# Generated by Django 5.0.6 on 2025-06-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_cashsale_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_excluding_vat',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_inclusive',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat_total',
        ),
    ]
