# Generated by Django 5.0.6 on 2025-03-11 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_salescategory_code_cashbookentry_date_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_price_currency', models.CharField(choices=[('USD', 'USD'), ('ZIG', 'ZIG')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.salescategory')),
                ('sales_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.salesaccount')),
                ('tax_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.vatsetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
