# Generated by Django 5.0.6 on 2025-03-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescategory',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
