# Generated by Django 5.0.6 on 2025-05-20 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_currencyrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashbook_id', models.CharField(max_length=255, unique=True)),
                ('cashbook_name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZIG', 'ZIG')], max_length=10)),
                ('reqiusition_status', models.BooleanField(default=False)),
                ('account_type', models.CharField(max_length=50)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('branch_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('general_ledger_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_ledger_account', to='accounting.generalledgeraccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
