# Generated by Django 5.0.6 on 2025-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_cashbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZWG', 'ZwG')], max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZWG', 'ZWG')], max_length=10),
        ),
    ]
