# Generated by Django 4.2.20 on 2025-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_accountsector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesaccount',
            name='account_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
