# Generated by Django 5.0.6 on 2025-05-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_cashbook_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbook',
            old_name='reqiusition_status',
            new_name='requisition_status',
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
