# Generated by Django 4.2.20 on 2025-05-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
