# Generated by Django 5.0.6 on 2025-05-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbook',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_price_currency',
        ),
    ]
