# Generated by Django 5.0.6 on 2025-05-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_remove_cashbook_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='currency',
            field=models.ForeignKey(null= True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_currency', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='base_currency',
            field=models.ForeignKey(null= True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='accounting.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='currency',
            field=models.ForeignKey(null= True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_currency', to='accounting.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price_currency',
            field=models.ForeignKey(null= True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_currency', to='accounting.currency'),
            preserve_default=False,
        ),
    ]
