# Generated by Django 5.0.6 on 2025-05-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_cashbook_currency_currencyrate_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_currency', to='accounting.currency'),
        ),
    ]
