# Generated by Django 4.2.20 on 2025-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsector',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
