# Generated by Django 4.2.20 on 2025-05-08 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0012_accountsector_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbookentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cashsale',
            name='company',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productservice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salesaccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salescategory',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vatsetting',
            name='company',
        ),
       
    ]
