# Generated by Django 4.2.20 on 2025-05-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from authentication.models import CustomUser 


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0013_remove_cashbookentry_company_remove_cashsale_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productservice',
            name='user',
            field=models.ForeignKey(default=CustomUser.objects.first().id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
