# Generated by Django 5.0.6 on 2025-05-22 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_rename_item_salesitem_remove_recurringinvoice_user_and_more'),
        ('rentsafe', '0011_merge_0009_merge_20250519_1553_0010_leasecurrencyrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentsafe.lease'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
