# Generated by Django 5.0.6 on 2025-05-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_invoice_invoice_number_invoice_lease_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
