# Generated by Django 4.2.20 on 2025-05-09 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_productservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
