# Generated by Django 5.0.6 on 2025-05-23 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_remove_cashbookentry_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.transactiontype'),
        ),
    ]
