# Generated by Django 5.0.6 on 2025-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_currencyrate_date_updated_invoiceitem_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
