# Generated by Django 5.0.6 on 2025-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_invoiceitem_vat_applicable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='vat_applicable',
        ),
        migrations.AddField(
            model_name='vatsetting',
            name='vat_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
