# Generated by Django 5.0.6 on 2025-05-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_remove_invoiceitem_vat_applicable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalledgeraccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='generalledgeraccount',
            name='account_sector',
        ),
    ]
