# Generated by Django 5.0.6 on 2025-05-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_remove_generalledgeraccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledgeraccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='generalledgeraccount',
            name='account_number',
            field=models.ImageField(blank=True, max_length=5, unique=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='generalledgeraccount',
            name='account_sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='accounting.accountsector'),
        ),
    ]
