# Generated by Django 5.0.6 on 2025-05-30 13:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_generalledgeraccount_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbookentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cashbookentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cashbookentry',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='cashbookentry',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='cashbook_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.cashbook'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='matching_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbook_entries', to='accounting.invoice'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='total_including_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='CashbookEntryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('cashbook_entry_type', models.CharField(choices=[('GL', 'General Ledger'), ('CR', 'Creditor')], max_length=50)),
                ('account', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.cashbookentrytype'),
        ),
    ]
