# Generated by Django 5.0.6 on 2025-05-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_generalledgeraccount_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
