# Generated by Django 5.0.6 on 2025-05-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_generalledgeraccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='account_sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sector', to='accounting.accountsector'),
        ),
    ]
