# Generated by Django 5.0.6 on 2025-05-29 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_generalledgeraccount_account_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgeraccount',
            name='account_sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='sector', to='accounting.accountsector'),
        ),
    ]
