# name: Deploy Rentsafe API

# on:
#   push:
#     branches:
#       - rentsafe-backend

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Connect and Deploy
#       uses: appleboy/ssh-action@v1.0.0
#       with:
#         host: your-ec2-ip
#         username: ubuntu
#         key: ${{ secrets.EC2_RENTSAFE_KEY }}
#         script: |
#           cd ~/rentsafe-api
#           git pull origin rentsafe-backend
#           docker compose down
#           docker compose up -d --build
