name: Rentsafe Tests

on:
  push:
    branches: [ "main","testing" ]
  pull_request:
    branches: [ "main","testing","staging","dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USE_SSL: ${{ secrets.EMAIL_USE_SSL }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      SMS_USERNAME: ${{ secrets.SMS_USERNAME }}
      SMS_PASSWORD: ${{ secrets.SMS_PASSWORD }}
      SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
      ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      WHATSAPP_API_MEDIA_URL: ${{ secrets.WHATSAPP_API_MEDIA_URL }}
      WHATSAPP_API_URL: ${{ secrets.WHATSAPP_API_URL }}
      WHATSAPP_ACCESS_TOKEN: ${{ secrets.WHATSAPP_ACCESS_TOKEN }}
      WHATSAPP_VERIFY_TOKEN: ${{ secrets.WHATSAPP_VERIFY_TOKEN }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
      
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py migrate
        
        python manage.py test
