name: Build and Push Static Files

on:
  push:
    branches: [ "testing" ]

jobs:
  build-and-push-static:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USE_SSL: ${{ secrets.EMAIL_USE_SSL }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      SMS_USERNAME: ${{ secrets.SMS_USERNAME }}
      SMS_PASSWORD: ${{ secrets.SMS_PASSWORD }}
      SMS_API_KEY: ${{ secrets.SMS_API_KEY }}
      ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
      WHATSAPP_API_MEDIA_URL: ${{ secrets.WHATSAPP_API_MEDIA_URL }}
      WHATSAPP_API_URL: ${{ secrets.WHATSAPP_API_URL }}
      WHATSAPP_ACCESS_TOKEN: ${{ secrets.WHATSAPP_ACCESS_TOKEN }}
      WHATSAPP_VERIFY_TOKEN: ${{ secrets.WHATSAPP_VERIFY_TOKEN }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build Frontend
      run: npm run vite-build

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect Static Files
      run: python manage.py collectstatic --no-input

    - name: Commit and Push Static Files
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add static/
        git diff --cached --quiet || git commit -m "chore: Auto update static files after build"
        git push origin testing
