name: Build and Push Static Files

on:
  push:
    branches: [ "testing" ]

jobs:
  build-and-push-static:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build Frontend
      run: npm run vite-build

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Collect Static Files
      run: python manage.py collectstatic --no-input

    - name: Commit and Push Static Files
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add static/
        git diff --cached --quiet || git commit -m "chore: Auto update static files after build"
        git push origin testing
