# Generated by Django 4.2.7 on 2025-07-09 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("individuals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nextofkin",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="individual",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employmentdetail",
            name="individual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employment_details",
                to="individuals.individual",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetail",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="The user who last created or modified this record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
