# Generated by Django 4.2.7 on 2025-07-19 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("individuals", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employmentdetail",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="email",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="landline_phone",
        ),
        migrations.RemoveField(
            model_name="individual",
            name="mobile_phone",
        ),
    ]
