# Generated by Django 4.2.7 on 2025-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "individuals",
            "0004_remove_employmentdetail_user_remove_individual_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
