# Generated by Django 4.2.7 on 2025-09-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individuals", "0005_alter_individual_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualcontactdetail",
            name="email",
        ),
        migrations.RemoveField(
            model_name="individualcontactdetail",
            name="mobile_phone",
        ),
        migrations.AddField(
            model_name="individual",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="individualcontactdetail",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="individualcontactdetail",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mobile", "Mobile"),
                    ("whatsapp", "WhatsApp"),
                    ("home", "Home"),
                    ("work", "Work"),
                    ("other", "Other"),
                ],
                default="mobile",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
