# Generated by Django 4.2.7 on 2025-10-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("individuals", "0006_remove_individualcontactdetail_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="individual",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="IndividualAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("date_updated", models.DateTimeField(auto_now=True, null=True)),
                ("tin_number", models.CharField(max_length=100, unique=True)),
                ("vat_number", models.CharField(max_length=100, unique=True)),
                (
                    "individual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_details",
                        to="individuals.individual",
                    ),
                ),
            ],
            options={
                "verbose_name": "individual account detail",
                "verbose_name_plural": "individual account details",
                "db_table": "individual_account_detail",
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
    ]
