# Generated by Django 4.2.7 on 2025-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("individuals", "0007_individual_account_number_individualaccounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="employmentdetail",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
